// Code generated by ent, DO NOT EDIT.

package knowledgebase

import (
	"agent-platform/internal/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldDescription, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldType, v))
}

// EmbeddingModel applies equality check predicate on the "embedding_model" field. It's identical to EmbeddingModelEQ.
func EmbeddingModel(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldEmbeddingModel, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldUpdatedAt, v))
}

// DocumentCount applies equality check predicate on the "document_count" field. It's identical to DocumentCountEQ.
func DocumentCount(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldDocumentCount, v))
}

// VectorCount applies equality check predicate on the "vector_count" field. It's identical to VectorCountEQ.
func VectorCount(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldVectorCount, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContainsFold(FieldDescription, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContainsFold(FieldType, v))
}

// EmbeddingModelEQ applies the EQ predicate on the "embedding_model" field.
func EmbeddingModelEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldEmbeddingModel, v))
}

// EmbeddingModelNEQ applies the NEQ predicate on the "embedding_model" field.
func EmbeddingModelNEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldEmbeddingModel, v))
}

// EmbeddingModelIn applies the In predicate on the "embedding_model" field.
func EmbeddingModelIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldEmbeddingModel, vs...))
}

// EmbeddingModelNotIn applies the NotIn predicate on the "embedding_model" field.
func EmbeddingModelNotIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldEmbeddingModel, vs...))
}

// EmbeddingModelGT applies the GT predicate on the "embedding_model" field.
func EmbeddingModelGT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldEmbeddingModel, v))
}

// EmbeddingModelGTE applies the GTE predicate on the "embedding_model" field.
func EmbeddingModelGTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldEmbeddingModel, v))
}

// EmbeddingModelLT applies the LT predicate on the "embedding_model" field.
func EmbeddingModelLT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldEmbeddingModel, v))
}

// EmbeddingModelLTE applies the LTE predicate on the "embedding_model" field.
func EmbeddingModelLTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldEmbeddingModel, v))
}

// EmbeddingModelContains applies the Contains predicate on the "embedding_model" field.
func EmbeddingModelContains(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContains(FieldEmbeddingModel, v))
}

// EmbeddingModelHasPrefix applies the HasPrefix predicate on the "embedding_model" field.
func EmbeddingModelHasPrefix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasPrefix(FieldEmbeddingModel, v))
}

// EmbeddingModelHasSuffix applies the HasSuffix predicate on the "embedding_model" field.
func EmbeddingModelHasSuffix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasSuffix(FieldEmbeddingModel, v))
}

// EmbeddingModelEqualFold applies the EqualFold predicate on the "embedding_model" field.
func EmbeddingModelEqualFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEqualFold(FieldEmbeddingModel, v))
}

// EmbeddingModelContainsFold applies the ContainsFold predicate on the "embedding_model" field.
func EmbeddingModelContainsFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContainsFold(FieldEmbeddingModel, v))
}

// ChunkConfigIsNil applies the IsNil predicate on the "chunk_config" field.
func ChunkConfigIsNil() predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIsNull(FieldChunkConfig))
}

// ChunkConfigNotNil applies the NotNil predicate on the "chunk_config" field.
func ChunkConfigNotNil() predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotNull(FieldChunkConfig))
}

// DocumentsIsNil applies the IsNil predicate on the "documents" field.
func DocumentsIsNil() predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIsNull(FieldDocuments))
}

// DocumentsNotNil applies the NotNil predicate on the "documents" field.
func DocumentsNotNil() predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotNull(FieldDocuments))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotNull(FieldMetadata))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldContainsFold(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldUpdatedAt, v))
}

// DocumentCountEQ applies the EQ predicate on the "document_count" field.
func DocumentCountEQ(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldDocumentCount, v))
}

// DocumentCountNEQ applies the NEQ predicate on the "document_count" field.
func DocumentCountNEQ(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldDocumentCount, v))
}

// DocumentCountIn applies the In predicate on the "document_count" field.
func DocumentCountIn(vs ...int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldDocumentCount, vs...))
}

// DocumentCountNotIn applies the NotIn predicate on the "document_count" field.
func DocumentCountNotIn(vs ...int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldDocumentCount, vs...))
}

// DocumentCountGT applies the GT predicate on the "document_count" field.
func DocumentCountGT(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldDocumentCount, v))
}

// DocumentCountGTE applies the GTE predicate on the "document_count" field.
func DocumentCountGTE(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldDocumentCount, v))
}

// DocumentCountLT applies the LT predicate on the "document_count" field.
func DocumentCountLT(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldDocumentCount, v))
}

// DocumentCountLTE applies the LTE predicate on the "document_count" field.
func DocumentCountLTE(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldDocumentCount, v))
}

// VectorCountEQ applies the EQ predicate on the "vector_count" field.
func VectorCountEQ(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldEQ(FieldVectorCount, v))
}

// VectorCountNEQ applies the NEQ predicate on the "vector_count" field.
func VectorCountNEQ(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNEQ(FieldVectorCount, v))
}

// VectorCountIn applies the In predicate on the "vector_count" field.
func VectorCountIn(vs ...int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldIn(FieldVectorCount, vs...))
}

// VectorCountNotIn applies the NotIn predicate on the "vector_count" field.
func VectorCountNotIn(vs ...int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldNotIn(FieldVectorCount, vs...))
}

// VectorCountGT applies the GT predicate on the "vector_count" field.
func VectorCountGT(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGT(FieldVectorCount, v))
}

// VectorCountGTE applies the GTE predicate on the "vector_count" field.
func VectorCountGTE(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldGTE(FieldVectorCount, v))
}

// VectorCountLT applies the LT predicate on the "vector_count" field.
func VectorCountLT(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLT(FieldVectorCount, v))
}

// VectorCountLTE applies the LTE predicate on the "vector_count" field.
func VectorCountLTE(v int) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.FieldLTE(FieldVectorCount, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KnowledgeBase) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KnowledgeBase) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KnowledgeBase) predicate.KnowledgeBase {
	return predicate.KnowledgeBase(sql.NotPredicates(p))
}
