// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agent-platform/internal/model/ent/agent"
	"agent-platform/internal/model/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (au *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *AgentUpdate) SetName(s string) *AgentUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *AgentUpdate) SetNillableName(s *string) *AgentUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// SetDescription sets the "description" field.
func (au *AgentUpdate) SetDescription(s string) *AgentUpdate {
	au.mutation.SetDescription(s)
	return au
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (au *AgentUpdate) SetNillableDescription(s *string) *AgentUpdate {
	if s != nil {
		au.SetDescription(*s)
	}
	return au
}

// ClearDescription clears the value of the "description" field.
func (au *AgentUpdate) ClearDescription() *AgentUpdate {
	au.mutation.ClearDescription()
	return au
}

// SetType sets the "type" field.
func (au *AgentUpdate) SetType(s string) *AgentUpdate {
	au.mutation.SetType(s)
	return au
}

// SetNillableType sets the "type" field if the given value is not nil.
func (au *AgentUpdate) SetNillableType(s *string) *AgentUpdate {
	if s != nil {
		au.SetType(*s)
	}
	return au
}

// SetModelConfig sets the "model_config" field.
func (au *AgentUpdate) SetModelConfig(m map[string]interface{}) *AgentUpdate {
	au.mutation.SetModelConfig(m)
	return au
}

// ClearModelConfig clears the value of the "model_config" field.
func (au *AgentUpdate) ClearModelConfig() *AgentUpdate {
	au.mutation.ClearModelConfig()
	return au
}

// SetTools sets the "tools" field.
func (au *AgentUpdate) SetTools(s []string) *AgentUpdate {
	au.mutation.SetTools(s)
	return au
}

// AppendTools appends s to the "tools" field.
func (au *AgentUpdate) AppendTools(s []string) *AgentUpdate {
	au.mutation.AppendTools(s)
	return au
}

// ClearTools clears the value of the "tools" field.
func (au *AgentUpdate) ClearTools() *AgentUpdate {
	au.mutation.ClearTools()
	return au
}

// SetKnowledgeBases sets the "knowledge_bases" field.
func (au *AgentUpdate) SetKnowledgeBases(s []string) *AgentUpdate {
	au.mutation.SetKnowledgeBases(s)
	return au
}

// AppendKnowledgeBases appends s to the "knowledge_bases" field.
func (au *AgentUpdate) AppendKnowledgeBases(s []string) *AgentUpdate {
	au.mutation.AppendKnowledgeBases(s)
	return au
}

// ClearKnowledgeBases clears the value of the "knowledge_bases" field.
func (au *AgentUpdate) ClearKnowledgeBases() *AgentUpdate {
	au.mutation.ClearKnowledgeBases()
	return au
}

// SetPromptTemplate sets the "prompt_template" field.
func (au *AgentUpdate) SetPromptTemplate(s string) *AgentUpdate {
	au.mutation.SetPromptTemplate(s)
	return au
}

// SetNillablePromptTemplate sets the "prompt_template" field if the given value is not nil.
func (au *AgentUpdate) SetNillablePromptTemplate(s *string) *AgentUpdate {
	if s != nil {
		au.SetPromptTemplate(*s)
	}
	return au
}

// ClearPromptTemplate clears the value of the "prompt_template" field.
func (au *AgentUpdate) ClearPromptTemplate() *AgentUpdate {
	au.mutation.ClearPromptTemplate()
	return au
}

// SetParameters sets the "parameters" field.
func (au *AgentUpdate) SetParameters(m map[string]interface{}) *AgentUpdate {
	au.mutation.SetParameters(m)
	return au
}

// ClearParameters clears the value of the "parameters" field.
func (au *AgentUpdate) ClearParameters() *AgentUpdate {
	au.mutation.ClearParameters()
	return au
}

// SetStatus sets the "status" field.
func (au *AgentUpdate) SetStatus(s string) *AgentUpdate {
	au.mutation.SetStatus(s)
	return au
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (au *AgentUpdate) SetNillableStatus(s *string) *AgentUpdate {
	if s != nil {
		au.SetStatus(*s)
	}
	return au
}

// SetVersion sets the "version" field.
func (au *AgentUpdate) SetVersion(s string) *AgentUpdate {
	au.mutation.SetVersion(s)
	return au
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (au *AgentUpdate) SetNillableVersion(s *string) *AgentUpdate {
	if s != nil {
		au.SetVersion(*s)
	}
	return au
}

// SetCreatedBy sets the "created_by" field.
func (au *AgentUpdate) SetCreatedBy(s string) *AgentUpdate {
	au.mutation.SetCreatedBy(s)
	return au
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (au *AgentUpdate) SetNillableCreatedBy(s *string) *AgentUpdate {
	if s != nil {
		au.SetCreatedBy(*s)
	}
	return au
}

// SetUpdatedAt sets the "updated_at" field.
func (au *AgentUpdate) SetUpdatedAt(t time.Time) *AgentUpdate {
	au.mutation.SetUpdatedAt(t)
	return au
}

// SetTags sets the "tags" field.
func (au *AgentUpdate) SetTags(s []string) *AgentUpdate {
	au.mutation.SetTags(s)
	return au
}

// AppendTags appends s to the "tags" field.
func (au *AgentUpdate) AppendTags(s []string) *AgentUpdate {
	au.mutation.AppendTags(s)
	return au
}

// ClearTags clears the value of the "tags" field.
func (au *AgentUpdate) ClearTags() *AgentUpdate {
	au.mutation.ClearTags()
	return au
}

// SetFolder sets the "folder" field.
func (au *AgentUpdate) SetFolder(s string) *AgentUpdate {
	au.mutation.SetFolder(s)
	return au
}

// SetNillableFolder sets the "folder" field if the given value is not nil.
func (au *AgentUpdate) SetNillableFolder(s *string) *AgentUpdate {
	if s != nil {
		au.SetFolder(*s)
	}
	return au
}

// ClearFolder clears the value of the "folder" field.
func (au *AgentUpdate) ClearFolder() *AgentUpdate {
	au.mutation.ClearFolder()
	return au
}

// SetIsPublic sets the "is_public" field.
func (au *AgentUpdate) SetIsPublic(b bool) *AgentUpdate {
	au.mutation.SetIsPublic(b)
	return au
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (au *AgentUpdate) SetNillableIsPublic(b *bool) *AgentUpdate {
	if b != nil {
		au.SetIsPublic(*b)
	}
	return au
}

// Mutation returns the AgentMutation object of the builder.
func (au *AgentUpdate) Mutation() *AgentMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AgentUpdate) Save(ctx context.Context) (int, error) {
	au.defaults()
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AgentUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AgentUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AgentUpdate) defaults() {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AgentUpdate) check() error {
	if v, ok := au.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if v, ok := au.mutation.CreatedBy(); ok {
		if err := agent.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "Agent.created_by": %w`, err)}
		}
	}
	return nil
}

func (au *AgentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.Description(); ok {
		_spec.SetField(agent.FieldDescription, field.TypeString, value)
	}
	if au.mutation.DescriptionCleared() {
		_spec.ClearField(agent.FieldDescription, field.TypeString)
	}
	if value, ok := au.mutation.GetType(); ok {
		_spec.SetField(agent.FieldType, field.TypeString, value)
	}
	if value, ok := au.mutation.ModelConfig(); ok {
		_spec.SetField(agent.FieldModelConfig, field.TypeJSON, value)
	}
	if au.mutation.ModelConfigCleared() {
		_spec.ClearField(agent.FieldModelConfig, field.TypeJSON)
	}
	if value, ok := au.mutation.Tools(); ok {
		_spec.SetField(agent.FieldTools, field.TypeJSON, value)
	}
	if value, ok := au.mutation.AppendedTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldTools, value)
		})
	}
	if au.mutation.ToolsCleared() {
		_spec.ClearField(agent.FieldTools, field.TypeJSON)
	}
	if value, ok := au.mutation.KnowledgeBases(); ok {
		_spec.SetField(agent.FieldKnowledgeBases, field.TypeJSON, value)
	}
	if value, ok := au.mutation.AppendedKnowledgeBases(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldKnowledgeBases, value)
		})
	}
	if au.mutation.KnowledgeBasesCleared() {
		_spec.ClearField(agent.FieldKnowledgeBases, field.TypeJSON)
	}
	if value, ok := au.mutation.PromptTemplate(); ok {
		_spec.SetField(agent.FieldPromptTemplate, field.TypeString, value)
	}
	if au.mutation.PromptTemplateCleared() {
		_spec.ClearField(agent.FieldPromptTemplate, field.TypeString)
	}
	if value, ok := au.mutation.Parameters(); ok {
		_spec.SetField(agent.FieldParameters, field.TypeJSON, value)
	}
	if au.mutation.ParametersCleared() {
		_spec.ClearField(agent.FieldParameters, field.TypeJSON)
	}
	if value, ok := au.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeString, value)
	}
	if value, ok := au.mutation.Version(); ok {
		_spec.SetField(agent.FieldVersion, field.TypeString, value)
	}
	if value, ok := au.mutation.CreatedBy(); ok {
		_spec.SetField(agent.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := au.mutation.Tags(); ok {
		_spec.SetField(agent.FieldTags, field.TypeJSON, value)
	}
	if value, ok := au.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldTags, value)
		})
	}
	if au.mutation.TagsCleared() {
		_spec.ClearField(agent.FieldTags, field.TypeJSON)
	}
	if value, ok := au.mutation.Folder(); ok {
		_spec.SetField(agent.FieldFolder, field.TypeString, value)
	}
	if au.mutation.FolderCleared() {
		_spec.ClearField(agent.FieldFolder, field.TypeString)
	}
	if value, ok := au.mutation.IsPublic(); ok {
		_spec.SetField(agent.FieldIsPublic, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetName sets the "name" field.
func (auo *AgentUpdateOne) SetName(s string) *AgentUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableName(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// SetDescription sets the "description" field.
func (auo *AgentUpdateOne) SetDescription(s string) *AgentUpdateOne {
	auo.mutation.SetDescription(s)
	return auo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableDescription(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetDescription(*s)
	}
	return auo
}

// ClearDescription clears the value of the "description" field.
func (auo *AgentUpdateOne) ClearDescription() *AgentUpdateOne {
	auo.mutation.ClearDescription()
	return auo
}

// SetType sets the "type" field.
func (auo *AgentUpdateOne) SetType(s string) *AgentUpdateOne {
	auo.mutation.SetType(s)
	return auo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableType(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetType(*s)
	}
	return auo
}

// SetModelConfig sets the "model_config" field.
func (auo *AgentUpdateOne) SetModelConfig(m map[string]interface{}) *AgentUpdateOne {
	auo.mutation.SetModelConfig(m)
	return auo
}

// ClearModelConfig clears the value of the "model_config" field.
func (auo *AgentUpdateOne) ClearModelConfig() *AgentUpdateOne {
	auo.mutation.ClearModelConfig()
	return auo
}

// SetTools sets the "tools" field.
func (auo *AgentUpdateOne) SetTools(s []string) *AgentUpdateOne {
	auo.mutation.SetTools(s)
	return auo
}

// AppendTools appends s to the "tools" field.
func (auo *AgentUpdateOne) AppendTools(s []string) *AgentUpdateOne {
	auo.mutation.AppendTools(s)
	return auo
}

// ClearTools clears the value of the "tools" field.
func (auo *AgentUpdateOne) ClearTools() *AgentUpdateOne {
	auo.mutation.ClearTools()
	return auo
}

// SetKnowledgeBases sets the "knowledge_bases" field.
func (auo *AgentUpdateOne) SetKnowledgeBases(s []string) *AgentUpdateOne {
	auo.mutation.SetKnowledgeBases(s)
	return auo
}

// AppendKnowledgeBases appends s to the "knowledge_bases" field.
func (auo *AgentUpdateOne) AppendKnowledgeBases(s []string) *AgentUpdateOne {
	auo.mutation.AppendKnowledgeBases(s)
	return auo
}

// ClearKnowledgeBases clears the value of the "knowledge_bases" field.
func (auo *AgentUpdateOne) ClearKnowledgeBases() *AgentUpdateOne {
	auo.mutation.ClearKnowledgeBases()
	return auo
}

// SetPromptTemplate sets the "prompt_template" field.
func (auo *AgentUpdateOne) SetPromptTemplate(s string) *AgentUpdateOne {
	auo.mutation.SetPromptTemplate(s)
	return auo
}

// SetNillablePromptTemplate sets the "prompt_template" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillablePromptTemplate(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetPromptTemplate(*s)
	}
	return auo
}

// ClearPromptTemplate clears the value of the "prompt_template" field.
func (auo *AgentUpdateOne) ClearPromptTemplate() *AgentUpdateOne {
	auo.mutation.ClearPromptTemplate()
	return auo
}

// SetParameters sets the "parameters" field.
func (auo *AgentUpdateOne) SetParameters(m map[string]interface{}) *AgentUpdateOne {
	auo.mutation.SetParameters(m)
	return auo
}

// ClearParameters clears the value of the "parameters" field.
func (auo *AgentUpdateOne) ClearParameters() *AgentUpdateOne {
	auo.mutation.ClearParameters()
	return auo
}

// SetStatus sets the "status" field.
func (auo *AgentUpdateOne) SetStatus(s string) *AgentUpdateOne {
	auo.mutation.SetStatus(s)
	return auo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableStatus(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetStatus(*s)
	}
	return auo
}

// SetVersion sets the "version" field.
func (auo *AgentUpdateOne) SetVersion(s string) *AgentUpdateOne {
	auo.mutation.SetVersion(s)
	return auo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableVersion(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetVersion(*s)
	}
	return auo
}

// SetCreatedBy sets the "created_by" field.
func (auo *AgentUpdateOne) SetCreatedBy(s string) *AgentUpdateOne {
	auo.mutation.SetCreatedBy(s)
	return auo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableCreatedBy(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetCreatedBy(*s)
	}
	return auo
}

// SetUpdatedAt sets the "updated_at" field.
func (auo *AgentUpdateOne) SetUpdatedAt(t time.Time) *AgentUpdateOne {
	auo.mutation.SetUpdatedAt(t)
	return auo
}

// SetTags sets the "tags" field.
func (auo *AgentUpdateOne) SetTags(s []string) *AgentUpdateOne {
	auo.mutation.SetTags(s)
	return auo
}

// AppendTags appends s to the "tags" field.
func (auo *AgentUpdateOne) AppendTags(s []string) *AgentUpdateOne {
	auo.mutation.AppendTags(s)
	return auo
}

// ClearTags clears the value of the "tags" field.
func (auo *AgentUpdateOne) ClearTags() *AgentUpdateOne {
	auo.mutation.ClearTags()
	return auo
}

// SetFolder sets the "folder" field.
func (auo *AgentUpdateOne) SetFolder(s string) *AgentUpdateOne {
	auo.mutation.SetFolder(s)
	return auo
}

// SetNillableFolder sets the "folder" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableFolder(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetFolder(*s)
	}
	return auo
}

// ClearFolder clears the value of the "folder" field.
func (auo *AgentUpdateOne) ClearFolder() *AgentUpdateOne {
	auo.mutation.ClearFolder()
	return auo
}

// SetIsPublic sets the "is_public" field.
func (auo *AgentUpdateOne) SetIsPublic(b bool) *AgentUpdateOne {
	auo.mutation.SetIsPublic(b)
	return auo
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableIsPublic(b *bool) *AgentUpdateOne {
	if b != nil {
		auo.SetIsPublic(*b)
	}
	return auo
}

// Mutation returns the AgentMutation object of the builder.
func (auo *AgentUpdateOne) Mutation() *AgentMutation {
	return auo.mutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (auo *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Agent entity.
func (auo *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	auo.defaults()
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AgentUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AgentUpdateOne) check() error {
	if v, ok := auo.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if v, ok := auo.mutation.CreatedBy(); ok {
		if err := agent.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "Agent.created_by": %w`, err)}
		}
	}
	return nil
}

func (auo *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.Description(); ok {
		_spec.SetField(agent.FieldDescription, field.TypeString, value)
	}
	if auo.mutation.DescriptionCleared() {
		_spec.ClearField(agent.FieldDescription, field.TypeString)
	}
	if value, ok := auo.mutation.GetType(); ok {
		_spec.SetField(agent.FieldType, field.TypeString, value)
	}
	if value, ok := auo.mutation.ModelConfig(); ok {
		_spec.SetField(agent.FieldModelConfig, field.TypeJSON, value)
	}
	if auo.mutation.ModelConfigCleared() {
		_spec.ClearField(agent.FieldModelConfig, field.TypeJSON)
	}
	if value, ok := auo.mutation.Tools(); ok {
		_spec.SetField(agent.FieldTools, field.TypeJSON, value)
	}
	if value, ok := auo.mutation.AppendedTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldTools, value)
		})
	}
	if auo.mutation.ToolsCleared() {
		_spec.ClearField(agent.FieldTools, field.TypeJSON)
	}
	if value, ok := auo.mutation.KnowledgeBases(); ok {
		_spec.SetField(agent.FieldKnowledgeBases, field.TypeJSON, value)
	}
	if value, ok := auo.mutation.AppendedKnowledgeBases(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldKnowledgeBases, value)
		})
	}
	if auo.mutation.KnowledgeBasesCleared() {
		_spec.ClearField(agent.FieldKnowledgeBases, field.TypeJSON)
	}
	if value, ok := auo.mutation.PromptTemplate(); ok {
		_spec.SetField(agent.FieldPromptTemplate, field.TypeString, value)
	}
	if auo.mutation.PromptTemplateCleared() {
		_spec.ClearField(agent.FieldPromptTemplate, field.TypeString)
	}
	if value, ok := auo.mutation.Parameters(); ok {
		_spec.SetField(agent.FieldParameters, field.TypeJSON, value)
	}
	if auo.mutation.ParametersCleared() {
		_spec.ClearField(agent.FieldParameters, field.TypeJSON)
	}
	if value, ok := auo.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeString, value)
	}
	if value, ok := auo.mutation.Version(); ok {
		_spec.SetField(agent.FieldVersion, field.TypeString, value)
	}
	if value, ok := auo.mutation.CreatedBy(); ok {
		_spec.SetField(agent.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := auo.mutation.Tags(); ok {
		_spec.SetField(agent.FieldTags, field.TypeJSON, value)
	}
	if value, ok := auo.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldTags, value)
		})
	}
	if auo.mutation.TagsCleared() {
		_spec.ClearField(agent.FieldTags, field.TypeJSON)
	}
	if value, ok := auo.mutation.Folder(); ok {
		_spec.SetField(agent.FieldFolder, field.TypeString, value)
	}
	if auo.mutation.FolderCleared() {
		_spec.ClearField(agent.FieldFolder, field.TypeString)
	}
	if value, ok := auo.mutation.IsPublic(); ok {
		_spec.SetField(agent.FieldIsPublic, field.TypeBool, value)
	}
	_node = &Agent{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
