// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agent-platform/internal/model/ent/conversation"
	"agent-platform/internal/model/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ConversationUpdate is the builder for updating Conversation entities.
type ConversationUpdate struct {
	config
	hooks    []Hook
	mutation *ConversationMutation
}

// Where appends a list predicates to the ConversationUpdate builder.
func (cu *ConversationUpdate) Where(ps ...predicate.Conversation) *ConversationUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetAgentID sets the "agent_id" field.
func (cu *ConversationUpdate) SetAgentID(s string) *ConversationUpdate {
	cu.mutation.SetAgentID(s)
	return cu
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (cu *ConversationUpdate) SetNillableAgentID(s *string) *ConversationUpdate {
	if s != nil {
		cu.SetAgentID(*s)
	}
	return cu
}

// SetUserID sets the "user_id" field.
func (cu *ConversationUpdate) SetUserID(s string) *ConversationUpdate {
	cu.mutation.SetUserID(s)
	return cu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (cu *ConversationUpdate) SetNillableUserID(s *string) *ConversationUpdate {
	if s != nil {
		cu.SetUserID(*s)
	}
	return cu
}

// SetTitle sets the "title" field.
func (cu *ConversationUpdate) SetTitle(s string) *ConversationUpdate {
	cu.mutation.SetTitle(s)
	return cu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (cu *ConversationUpdate) SetNillableTitle(s *string) *ConversationUpdate {
	if s != nil {
		cu.SetTitle(*s)
	}
	return cu
}

// ClearTitle clears the value of the "title" field.
func (cu *ConversationUpdate) ClearTitle() *ConversationUpdate {
	cu.mutation.ClearTitle()
	return cu
}

// SetMessages sets the "messages" field.
func (cu *ConversationUpdate) SetMessages(i []interface{}) *ConversationUpdate {
	cu.mutation.SetMessages(i)
	return cu
}

// AppendMessages appends i to the "messages" field.
func (cu *ConversationUpdate) AppendMessages(i []interface{}) *ConversationUpdate {
	cu.mutation.AppendMessages(i)
	return cu
}

// ClearMessages clears the value of the "messages" field.
func (cu *ConversationUpdate) ClearMessages() *ConversationUpdate {
	cu.mutation.ClearMessages()
	return cu
}

// SetContext sets the "context" field.
func (cu *ConversationUpdate) SetContext(m map[string]interface{}) *ConversationUpdate {
	cu.mutation.SetContext(m)
	return cu
}

// ClearContext clears the value of the "context" field.
func (cu *ConversationUpdate) ClearContext() *ConversationUpdate {
	cu.mutation.ClearContext()
	return cu
}

// SetMetadata sets the "metadata" field.
func (cu *ConversationUpdate) SetMetadata(m map[string]interface{}) *ConversationUpdate {
	cu.mutation.SetMetadata(m)
	return cu
}

// ClearMetadata clears the value of the "metadata" field.
func (cu *ConversationUpdate) ClearMetadata() *ConversationUpdate {
	cu.mutation.ClearMetadata()
	return cu
}

// SetStatus sets the "status" field.
func (cu *ConversationUpdate) SetStatus(s string) *ConversationUpdate {
	cu.mutation.SetStatus(s)
	return cu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cu *ConversationUpdate) SetNillableStatus(s *string) *ConversationUpdate {
	if s != nil {
		cu.SetStatus(*s)
	}
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *ConversationUpdate) SetUpdatedAt(t time.Time) *ConversationUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetLastMessageAt sets the "last_message_at" field.
func (cu *ConversationUpdate) SetLastMessageAt(t time.Time) *ConversationUpdate {
	cu.mutation.SetLastMessageAt(t)
	return cu
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (cu *ConversationUpdate) SetNillableLastMessageAt(t *time.Time) *ConversationUpdate {
	if t != nil {
		cu.SetLastMessageAt(*t)
	}
	return cu
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (cu *ConversationUpdate) ClearLastMessageAt() *ConversationUpdate {
	cu.mutation.ClearLastMessageAt()
	return cu
}

// Mutation returns the ConversationMutation object of the builder.
func (cu *ConversationUpdate) Mutation() *ConversationMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ConversationUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ConversationUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ConversationUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ConversationUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *ConversationUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := conversation.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ConversationUpdate) check() error {
	if v, ok := cu.mutation.AgentID(); ok {
		if err := conversation.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "Conversation.agent_id": %w`, err)}
		}
	}
	if v, ok := cu.mutation.UserID(); ok {
		if err := conversation.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Conversation.user_id": %w`, err)}
		}
	}
	return nil
}

func (cu *ConversationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversation.Table, conversation.Columns, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeString))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.AgentID(); ok {
		_spec.SetField(conversation.FieldAgentID, field.TypeString, value)
	}
	if value, ok := cu.mutation.UserID(); ok {
		_spec.SetField(conversation.FieldUserID, field.TypeString, value)
	}
	if value, ok := cu.mutation.Title(); ok {
		_spec.SetField(conversation.FieldTitle, field.TypeString, value)
	}
	if cu.mutation.TitleCleared() {
		_spec.ClearField(conversation.FieldTitle, field.TypeString)
	}
	if value, ok := cu.mutation.Messages(); ok {
		_spec.SetField(conversation.FieldMessages, field.TypeJSON, value)
	}
	if value, ok := cu.mutation.AppendedMessages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, conversation.FieldMessages, value)
		})
	}
	if cu.mutation.MessagesCleared() {
		_spec.ClearField(conversation.FieldMessages, field.TypeJSON)
	}
	if value, ok := cu.mutation.Context(); ok {
		_spec.SetField(conversation.FieldContext, field.TypeJSON, value)
	}
	if cu.mutation.ContextCleared() {
		_spec.ClearField(conversation.FieldContext, field.TypeJSON)
	}
	if value, ok := cu.mutation.Metadata(); ok {
		_spec.SetField(conversation.FieldMetadata, field.TypeJSON, value)
	}
	if cu.mutation.MetadataCleared() {
		_spec.ClearField(conversation.FieldMetadata, field.TypeJSON)
	}
	if value, ok := cu.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeString, value)
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.LastMessageAt(); ok {
		_spec.SetField(conversation.FieldLastMessageAt, field.TypeTime, value)
	}
	if cu.mutation.LastMessageAtCleared() {
		_spec.ClearField(conversation.FieldLastMessageAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ConversationUpdateOne is the builder for updating a single Conversation entity.
type ConversationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConversationMutation
}

// SetAgentID sets the "agent_id" field.
func (cuo *ConversationUpdateOne) SetAgentID(s string) *ConversationUpdateOne {
	cuo.mutation.SetAgentID(s)
	return cuo
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (cuo *ConversationUpdateOne) SetNillableAgentID(s *string) *ConversationUpdateOne {
	if s != nil {
		cuo.SetAgentID(*s)
	}
	return cuo
}

// SetUserID sets the "user_id" field.
func (cuo *ConversationUpdateOne) SetUserID(s string) *ConversationUpdateOne {
	cuo.mutation.SetUserID(s)
	return cuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (cuo *ConversationUpdateOne) SetNillableUserID(s *string) *ConversationUpdateOne {
	if s != nil {
		cuo.SetUserID(*s)
	}
	return cuo
}

// SetTitle sets the "title" field.
func (cuo *ConversationUpdateOne) SetTitle(s string) *ConversationUpdateOne {
	cuo.mutation.SetTitle(s)
	return cuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (cuo *ConversationUpdateOne) SetNillableTitle(s *string) *ConversationUpdateOne {
	if s != nil {
		cuo.SetTitle(*s)
	}
	return cuo
}

// ClearTitle clears the value of the "title" field.
func (cuo *ConversationUpdateOne) ClearTitle() *ConversationUpdateOne {
	cuo.mutation.ClearTitle()
	return cuo
}

// SetMessages sets the "messages" field.
func (cuo *ConversationUpdateOne) SetMessages(i []interface{}) *ConversationUpdateOne {
	cuo.mutation.SetMessages(i)
	return cuo
}

// AppendMessages appends i to the "messages" field.
func (cuo *ConversationUpdateOne) AppendMessages(i []interface{}) *ConversationUpdateOne {
	cuo.mutation.AppendMessages(i)
	return cuo
}

// ClearMessages clears the value of the "messages" field.
func (cuo *ConversationUpdateOne) ClearMessages() *ConversationUpdateOne {
	cuo.mutation.ClearMessages()
	return cuo
}

// SetContext sets the "context" field.
func (cuo *ConversationUpdateOne) SetContext(m map[string]interface{}) *ConversationUpdateOne {
	cuo.mutation.SetContext(m)
	return cuo
}

// ClearContext clears the value of the "context" field.
func (cuo *ConversationUpdateOne) ClearContext() *ConversationUpdateOne {
	cuo.mutation.ClearContext()
	return cuo
}

// SetMetadata sets the "metadata" field.
func (cuo *ConversationUpdateOne) SetMetadata(m map[string]interface{}) *ConversationUpdateOne {
	cuo.mutation.SetMetadata(m)
	return cuo
}

// ClearMetadata clears the value of the "metadata" field.
func (cuo *ConversationUpdateOne) ClearMetadata() *ConversationUpdateOne {
	cuo.mutation.ClearMetadata()
	return cuo
}

// SetStatus sets the "status" field.
func (cuo *ConversationUpdateOne) SetStatus(s string) *ConversationUpdateOne {
	cuo.mutation.SetStatus(s)
	return cuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cuo *ConversationUpdateOne) SetNillableStatus(s *string) *ConversationUpdateOne {
	if s != nil {
		cuo.SetStatus(*s)
	}
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *ConversationUpdateOne) SetUpdatedAt(t time.Time) *ConversationUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetLastMessageAt sets the "last_message_at" field.
func (cuo *ConversationUpdateOne) SetLastMessageAt(t time.Time) *ConversationUpdateOne {
	cuo.mutation.SetLastMessageAt(t)
	return cuo
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (cuo *ConversationUpdateOne) SetNillableLastMessageAt(t *time.Time) *ConversationUpdateOne {
	if t != nil {
		cuo.SetLastMessageAt(*t)
	}
	return cuo
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (cuo *ConversationUpdateOne) ClearLastMessageAt() *ConversationUpdateOne {
	cuo.mutation.ClearLastMessageAt()
	return cuo
}

// Mutation returns the ConversationMutation object of the builder.
func (cuo *ConversationUpdateOne) Mutation() *ConversationMutation {
	return cuo.mutation
}

// Where appends a list predicates to the ConversationUpdate builder.
func (cuo *ConversationUpdateOne) Where(ps ...predicate.Conversation) *ConversationUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ConversationUpdateOne) Select(field string, fields ...string) *ConversationUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Conversation entity.
func (cuo *ConversationUpdateOne) Save(ctx context.Context) (*Conversation, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ConversationUpdateOne) SaveX(ctx context.Context) *Conversation {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ConversationUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ConversationUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *ConversationUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := conversation.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ConversationUpdateOne) check() error {
	if v, ok := cuo.mutation.AgentID(); ok {
		if err := conversation.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "Conversation.agent_id": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.UserID(); ok {
		if err := conversation.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Conversation.user_id": %w`, err)}
		}
	}
	return nil
}

func (cuo *ConversationUpdateOne) sqlSave(ctx context.Context) (_node *Conversation, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversation.Table, conversation.Columns, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeString))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Conversation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversation.FieldID)
		for _, f := range fields {
			if !conversation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != conversation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.AgentID(); ok {
		_spec.SetField(conversation.FieldAgentID, field.TypeString, value)
	}
	if value, ok := cuo.mutation.UserID(); ok {
		_spec.SetField(conversation.FieldUserID, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Title(); ok {
		_spec.SetField(conversation.FieldTitle, field.TypeString, value)
	}
	if cuo.mutation.TitleCleared() {
		_spec.ClearField(conversation.FieldTitle, field.TypeString)
	}
	if value, ok := cuo.mutation.Messages(); ok {
		_spec.SetField(conversation.FieldMessages, field.TypeJSON, value)
	}
	if value, ok := cuo.mutation.AppendedMessages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, conversation.FieldMessages, value)
		})
	}
	if cuo.mutation.MessagesCleared() {
		_spec.ClearField(conversation.FieldMessages, field.TypeJSON)
	}
	if value, ok := cuo.mutation.Context(); ok {
		_spec.SetField(conversation.FieldContext, field.TypeJSON, value)
	}
	if cuo.mutation.ContextCleared() {
		_spec.ClearField(conversation.FieldContext, field.TypeJSON)
	}
	if value, ok := cuo.mutation.Metadata(); ok {
		_spec.SetField(conversation.FieldMetadata, field.TypeJSON, value)
	}
	if cuo.mutation.MetadataCleared() {
		_spec.ClearField(conversation.FieldMetadata, field.TypeJSON)
	}
	if value, ok := cuo.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeString, value)
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.LastMessageAt(); ok {
		_spec.SetField(conversation.FieldLastMessageAt, field.TypeTime, value)
	}
	if cuo.mutation.LastMessageAtCleared() {
		_spec.ClearField(conversation.FieldLastMessageAt, field.TypeTime)
	}
	_node = &Conversation{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
