// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agent-platform/internal/model/ent/documentchunk"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DocumentChunkCreate is the builder for creating a DocumentChunk entity.
type DocumentChunkCreate struct {
	config
	mutation *DocumentChunkMutation
	hooks    []Hook
}

// SetKnowledgeBaseID sets the "knowledge_base_id" field.
func (dcc *DocumentChunkCreate) SetKnowledgeBaseID(s string) *DocumentChunkCreate {
	dcc.mutation.SetKnowledgeBaseID(s)
	return dcc
}

// SetDocumentID sets the "document_id" field.
func (dcc *DocumentChunkCreate) SetDocumentID(s string) *DocumentChunkCreate {
	dcc.mutation.SetDocumentID(s)
	return dcc
}

// SetChunkIndex sets the "chunk_index" field.
func (dcc *DocumentChunkCreate) SetChunkIndex(i int) *DocumentChunkCreate {
	dcc.mutation.SetChunkIndex(i)
	return dcc
}

// SetNillableChunkIndex sets the "chunk_index" field if the given value is not nil.
func (dcc *DocumentChunkCreate) SetNillableChunkIndex(i *int) *DocumentChunkCreate {
	if i != nil {
		dcc.SetChunkIndex(*i)
	}
	return dcc
}

// SetContent sets the "content" field.
func (dcc *DocumentChunkCreate) SetContent(s string) *DocumentChunkCreate {
	dcc.mutation.SetContent(s)
	return dcc
}

// SetEmbedding sets the "embedding" field.
func (dcc *DocumentChunkCreate) SetEmbedding(f []float32) *DocumentChunkCreate {
	dcc.mutation.SetEmbedding(f)
	return dcc
}

// SetMetadata sets the "metadata" field.
func (dcc *DocumentChunkCreate) SetMetadata(m map[string]interface{}) *DocumentChunkCreate {
	dcc.mutation.SetMetadata(m)
	return dcc
}

// SetCreatedAt sets the "created_at" field.
func (dcc *DocumentChunkCreate) SetCreatedAt(t time.Time) *DocumentChunkCreate {
	dcc.mutation.SetCreatedAt(t)
	return dcc
}

// SetID sets the "id" field.
func (dcc *DocumentChunkCreate) SetID(s string) *DocumentChunkCreate {
	dcc.mutation.SetID(s)
	return dcc
}

// Mutation returns the DocumentChunkMutation object of the builder.
func (dcc *DocumentChunkCreate) Mutation() *DocumentChunkMutation {
	return dcc.mutation
}

// Save creates the DocumentChunk in the database.
func (dcc *DocumentChunkCreate) Save(ctx context.Context) (*DocumentChunk, error) {
	dcc.defaults()
	return withHooks(ctx, dcc.sqlSave, dcc.mutation, dcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dcc *DocumentChunkCreate) SaveX(ctx context.Context) *DocumentChunk {
	v, err := dcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcc *DocumentChunkCreate) Exec(ctx context.Context) error {
	_, err := dcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcc *DocumentChunkCreate) ExecX(ctx context.Context) {
	if err := dcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dcc *DocumentChunkCreate) defaults() {
	if _, ok := dcc.mutation.ChunkIndex(); !ok {
		v := documentchunk.DefaultChunkIndex
		dcc.mutation.SetChunkIndex(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dcc *DocumentChunkCreate) check() error {
	if _, ok := dcc.mutation.KnowledgeBaseID(); !ok {
		return &ValidationError{Name: "knowledge_base_id", err: errors.New(`ent: missing required field "DocumentChunk.knowledge_base_id"`)}
	}
	if v, ok := dcc.mutation.KnowledgeBaseID(); ok {
		if err := documentchunk.KnowledgeBaseIDValidator(v); err != nil {
			return &ValidationError{Name: "knowledge_base_id", err: fmt.Errorf(`ent: validator failed for field "DocumentChunk.knowledge_base_id": %w`, err)}
		}
	}
	if _, ok := dcc.mutation.DocumentID(); !ok {
		return &ValidationError{Name: "document_id", err: errors.New(`ent: missing required field "DocumentChunk.document_id"`)}
	}
	if v, ok := dcc.mutation.DocumentID(); ok {
		if err := documentchunk.DocumentIDValidator(v); err != nil {
			return &ValidationError{Name: "document_id", err: fmt.Errorf(`ent: validator failed for field "DocumentChunk.document_id": %w`, err)}
		}
	}
	if _, ok := dcc.mutation.ChunkIndex(); !ok {
		return &ValidationError{Name: "chunk_index", err: errors.New(`ent: missing required field "DocumentChunk.chunk_index"`)}
	}
	if _, ok := dcc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "DocumentChunk.content"`)}
	}
	if v, ok := dcc.mutation.Content(); ok {
		if err := documentchunk.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "DocumentChunk.content": %w`, err)}
		}
	}
	if _, ok := dcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DocumentChunk.created_at"`)}
	}
	return nil
}

func (dcc *DocumentChunkCreate) sqlSave(ctx context.Context) (*DocumentChunk, error) {
	if err := dcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DocumentChunk.ID type: %T", _spec.ID.Value)
		}
	}
	dcc.mutation.id = &_node.ID
	dcc.mutation.done = true
	return _node, nil
}

func (dcc *DocumentChunkCreate) createSpec() (*DocumentChunk, *sqlgraph.CreateSpec) {
	var (
		_node = &DocumentChunk{config: dcc.config}
		_spec = sqlgraph.NewCreateSpec(documentchunk.Table, sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeString))
	)
	if id, ok := dcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := dcc.mutation.KnowledgeBaseID(); ok {
		_spec.SetField(documentchunk.FieldKnowledgeBaseID, field.TypeString, value)
		_node.KnowledgeBaseID = value
	}
	if value, ok := dcc.mutation.DocumentID(); ok {
		_spec.SetField(documentchunk.FieldDocumentID, field.TypeString, value)
		_node.DocumentID = value
	}
	if value, ok := dcc.mutation.ChunkIndex(); ok {
		_spec.SetField(documentchunk.FieldChunkIndex, field.TypeInt, value)
		_node.ChunkIndex = value
	}
	if value, ok := dcc.mutation.Content(); ok {
		_spec.SetField(documentchunk.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := dcc.mutation.Embedding(); ok {
		_spec.SetField(documentchunk.FieldEmbedding, field.TypeJSON, value)
		_node.Embedding = value
	}
	if value, ok := dcc.mutation.Metadata(); ok {
		_spec.SetField(documentchunk.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := dcc.mutation.CreatedAt(); ok {
		_spec.SetField(documentchunk.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// DocumentChunkCreateBulk is the builder for creating many DocumentChunk entities in bulk.
type DocumentChunkCreateBulk struct {
	config
	err      error
	builders []*DocumentChunkCreate
}

// Save creates the DocumentChunk entities in the database.
func (dccb *DocumentChunkCreateBulk) Save(ctx context.Context) ([]*DocumentChunk, error) {
	if dccb.err != nil {
		return nil, dccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dccb.builders))
	nodes := make([]*DocumentChunk, len(dccb.builders))
	mutators := make([]Mutator, len(dccb.builders))
	for i := range dccb.builders {
		func(i int, root context.Context) {
			builder := dccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DocumentChunkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dccb *DocumentChunkCreateBulk) SaveX(ctx context.Context) []*DocumentChunk {
	v, err := dccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dccb *DocumentChunkCreateBulk) Exec(ctx context.Context) error {
	_, err := dccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dccb *DocumentChunkCreateBulk) ExecX(ctx context.Context) {
	if err := dccb.Exec(ctx); err != nil {
		panic(err)
	}
}
