// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agent-platform/internal/model/ent/documentchunk"
	"agent-platform/internal/model/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DocumentChunkDelete is the builder for deleting a DocumentChunk entity.
type DocumentChunkDelete struct {
	config
	hooks    []Hook
	mutation *DocumentChunkMutation
}

// Where appends a list predicates to the DocumentChunkDelete builder.
func (dcd *DocumentChunkDelete) Where(ps ...predicate.DocumentChunk) *DocumentChunkDelete {
	dcd.mutation.Where(ps...)
	return dcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dcd *DocumentChunkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dcd.sqlExec, dcd.mutation, dcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dcd *DocumentChunkDelete) ExecX(ctx context.Context) int {
	n, err := dcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dcd *DocumentChunkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(documentchunk.Table, sqlgraph.NewFieldSpec(documentchunk.FieldID, field.TypeString))
	if ps := dcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dcd.mutation.done = true
	return affected, err
}

// DocumentChunkDeleteOne is the builder for deleting a single DocumentChunk entity.
type DocumentChunkDeleteOne struct {
	dcd *DocumentChunkDelete
}

// Where appends a list predicates to the DocumentChunkDelete builder.
func (dcdo *DocumentChunkDeleteOne) Where(ps ...predicate.DocumentChunk) *DocumentChunkDeleteOne {
	dcdo.dcd.mutation.Where(ps...)
	return dcdo
}

// Exec executes the deletion query.
func (dcdo *DocumentChunkDeleteOne) Exec(ctx context.Context) error {
	n, err := dcdo.dcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{documentchunk.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dcdo *DocumentChunkDeleteOne) ExecX(ctx context.Context) {
	if err := dcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
