// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agent-platform/internal/model/ent/knowledgebase"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// KnowledgeBase is the model entity for the KnowledgeBase schema.
type KnowledgeBase struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// EmbeddingModel holds the value of the "embedding_model" field.
	EmbeddingModel string `json:"embedding_model,omitempty"`
	// ChunkConfig holds the value of the "chunk_config" field.
	ChunkConfig map[string]interface{} `json:"chunk_config,omitempty"`
	// Documents holds the value of the "documents" field.
	Documents []interface{} `json:"documents,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DocumentCount holds the value of the "document_count" field.
	DocumentCount int `json:"document_count,omitempty"`
	// VectorCount holds the value of the "vector_count" field.
	VectorCount  int `json:"vector_count,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KnowledgeBase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case knowledgebase.FieldChunkConfig, knowledgebase.FieldDocuments, knowledgebase.FieldMetadata:
			values[i] = new([]byte)
		case knowledgebase.FieldDocumentCount, knowledgebase.FieldVectorCount:
			values[i] = new(sql.NullInt64)
		case knowledgebase.FieldID, knowledgebase.FieldName, knowledgebase.FieldDescription, knowledgebase.FieldType, knowledgebase.FieldEmbeddingModel, knowledgebase.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case knowledgebase.FieldCreatedAt, knowledgebase.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KnowledgeBase fields.
func (kb *KnowledgeBase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case knowledgebase.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				kb.ID = value.String
			}
		case knowledgebase.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				kb.Name = value.String
			}
		case knowledgebase.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				kb.Description = value.String
			}
		case knowledgebase.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				kb.Type = value.String
			}
		case knowledgebase.FieldEmbeddingModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field embedding_model", values[i])
			} else if value.Valid {
				kb.EmbeddingModel = value.String
			}
		case knowledgebase.FieldChunkConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field chunk_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &kb.ChunkConfig); err != nil {
					return fmt.Errorf("unmarshal field chunk_config: %w", err)
				}
			}
		case knowledgebase.FieldDocuments:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field documents", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &kb.Documents); err != nil {
					return fmt.Errorf("unmarshal field documents: %w", err)
				}
			}
		case knowledgebase.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &kb.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case knowledgebase.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				kb.CreatedBy = value.String
			}
		case knowledgebase.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				kb.CreatedAt = value.Time
			}
		case knowledgebase.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				kb.UpdatedAt = value.Time
			}
		case knowledgebase.FieldDocumentCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field document_count", values[i])
			} else if value.Valid {
				kb.DocumentCount = int(value.Int64)
			}
		case knowledgebase.FieldVectorCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field vector_count", values[i])
			} else if value.Valid {
				kb.VectorCount = int(value.Int64)
			}
		default:
			kb.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KnowledgeBase.
// This includes values selected through modifiers, order, etc.
func (kb *KnowledgeBase) Value(name string) (ent.Value, error) {
	return kb.selectValues.Get(name)
}

// Update returns a builder for updating this KnowledgeBase.
// Note that you need to call KnowledgeBase.Unwrap() before calling this method if this KnowledgeBase
// was returned from a transaction, and the transaction was committed or rolled back.
func (kb *KnowledgeBase) Update() *KnowledgeBaseUpdateOne {
	return NewKnowledgeBaseClient(kb.config).UpdateOne(kb)
}

// Unwrap unwraps the KnowledgeBase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (kb *KnowledgeBase) Unwrap() *KnowledgeBase {
	_tx, ok := kb.config.driver.(*txDriver)
	if !ok {
		panic("ent: KnowledgeBase is not a transactional entity")
	}
	kb.config.driver = _tx.drv
	return kb
}

// String implements the fmt.Stringer.
func (kb *KnowledgeBase) String() string {
	var builder strings.Builder
	builder.WriteString("KnowledgeBase(")
	builder.WriteString(fmt.Sprintf("id=%v, ", kb.ID))
	builder.WriteString("name=")
	builder.WriteString(kb.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(kb.Description)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(kb.Type)
	builder.WriteString(", ")
	builder.WriteString("embedding_model=")
	builder.WriteString(kb.EmbeddingModel)
	builder.WriteString(", ")
	builder.WriteString("chunk_config=")
	builder.WriteString(fmt.Sprintf("%v", kb.ChunkConfig))
	builder.WriteString(", ")
	builder.WriteString("documents=")
	builder.WriteString(fmt.Sprintf("%v", kb.Documents))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", kb.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(kb.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(kb.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(kb.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("document_count=")
	builder.WriteString(fmt.Sprintf("%v", kb.DocumentCount))
	builder.WriteString(", ")
	builder.WriteString("vector_count=")
	builder.WriteString(fmt.Sprintf("%v", kb.VectorCount))
	builder.WriteByte(')')
	return builder.String()
}

// KnowledgeBases is a parsable slice of KnowledgeBase.
type KnowledgeBases []*KnowledgeBase
