// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agent-platform/internal/model/ent/predicate"
	"agent-platform/internal/model/ent/tool"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ToolUpdate is the builder for updating Tool entities.
type ToolUpdate struct {
	config
	hooks    []Hook
	mutation *ToolMutation
}

// Where appends a list predicates to the ToolUpdate builder.
func (tu *ToolUpdate) Where(ps ...predicate.Tool) *ToolUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetName sets the "name" field.
func (tu *ToolUpdate) SetName(s string) *ToolUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *ToolUpdate) SetNillableName(s *string) *ToolUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// SetDescription sets the "description" field.
func (tu *ToolUpdate) SetDescription(s string) *ToolUpdate {
	tu.mutation.SetDescription(s)
	return tu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tu *ToolUpdate) SetNillableDescription(s *string) *ToolUpdate {
	if s != nil {
		tu.SetDescription(*s)
	}
	return tu
}

// ClearDescription clears the value of the "description" field.
func (tu *ToolUpdate) ClearDescription() *ToolUpdate {
	tu.mutation.ClearDescription()
	return tu
}

// SetType sets the "type" field.
func (tu *ToolUpdate) SetType(s string) *ToolUpdate {
	tu.mutation.SetType(s)
	return tu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tu *ToolUpdate) SetNillableType(s *string) *ToolUpdate {
	if s != nil {
		tu.SetType(*s)
	}
	return tu
}

// SetSchema sets the "schema" field.
func (tu *ToolUpdate) SetSchema(m map[string]interface{}) *ToolUpdate {
	tu.mutation.SetSchema(m)
	return tu
}

// ClearSchema clears the value of the "schema" field.
func (tu *ToolUpdate) ClearSchema() *ToolUpdate {
	tu.mutation.ClearSchema()
	return tu
}

// SetImplementation sets the "implementation" field.
func (tu *ToolUpdate) SetImplementation(s string) *ToolUpdate {
	tu.mutation.SetImplementation(s)
	return tu
}

// SetNillableImplementation sets the "implementation" field if the given value is not nil.
func (tu *ToolUpdate) SetNillableImplementation(s *string) *ToolUpdate {
	if s != nil {
		tu.SetImplementation(*s)
	}
	return tu
}

// ClearImplementation clears the value of the "implementation" field.
func (tu *ToolUpdate) ClearImplementation() *ToolUpdate {
	tu.mutation.ClearImplementation()
	return tu
}

// SetVersion sets the "version" field.
func (tu *ToolUpdate) SetVersion(s string) *ToolUpdate {
	tu.mutation.SetVersion(s)
	return tu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (tu *ToolUpdate) SetNillableVersion(s *string) *ToolUpdate {
	if s != nil {
		tu.SetVersion(*s)
	}
	return tu
}

// SetIsPublic sets the "is_public" field.
func (tu *ToolUpdate) SetIsPublic(b bool) *ToolUpdate {
	tu.mutation.SetIsPublic(b)
	return tu
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (tu *ToolUpdate) SetNillableIsPublic(b *bool) *ToolUpdate {
	if b != nil {
		tu.SetIsPublic(*b)
	}
	return tu
}

// SetCreatedBy sets the "created_by" field.
func (tu *ToolUpdate) SetCreatedBy(s string) *ToolUpdate {
	tu.mutation.SetCreatedBy(s)
	return tu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (tu *ToolUpdate) SetNillableCreatedBy(s *string) *ToolUpdate {
	if s != nil {
		tu.SetCreatedBy(*s)
	}
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *ToolUpdate) SetUpdatedAt(t time.Time) *ToolUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetTags sets the "tags" field.
func (tu *ToolUpdate) SetTags(s []string) *ToolUpdate {
	tu.mutation.SetTags(s)
	return tu
}

// AppendTags appends s to the "tags" field.
func (tu *ToolUpdate) AppendTags(s []string) *ToolUpdate {
	tu.mutation.AppendTags(s)
	return tu
}

// ClearTags clears the value of the "tags" field.
func (tu *ToolUpdate) ClearTags() *ToolUpdate {
	tu.mutation.ClearTags()
	return tu
}

// SetCategory sets the "category" field.
func (tu *ToolUpdate) SetCategory(s string) *ToolUpdate {
	tu.mutation.SetCategory(s)
	return tu
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (tu *ToolUpdate) SetNillableCategory(s *string) *ToolUpdate {
	if s != nil {
		tu.SetCategory(*s)
	}
	return tu
}

// ClearCategory clears the value of the "category" field.
func (tu *ToolUpdate) ClearCategory() *ToolUpdate {
	tu.mutation.ClearCategory()
	return tu
}

// Mutation returns the ToolMutation object of the builder.
func (tu *ToolUpdate) Mutation() *ToolMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *ToolUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *ToolUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *ToolUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *ToolUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *ToolUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := tool.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *ToolUpdate) check() error {
	if v, ok := tu.mutation.Name(); ok {
		if err := tool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tool.name": %w`, err)}
		}
	}
	if v, ok := tu.mutation.CreatedBy(); ok {
		if err := tool.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "Tool.created_by": %w`, err)}
		}
	}
	return nil
}

func (tu *ToolUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tool.Table, tool.Columns, sqlgraph.NewFieldSpec(tool.FieldID, field.TypeString))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(tool.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.Description(); ok {
		_spec.SetField(tool.FieldDescription, field.TypeString, value)
	}
	if tu.mutation.DescriptionCleared() {
		_spec.ClearField(tool.FieldDescription, field.TypeString)
	}
	if value, ok := tu.mutation.GetType(); ok {
		_spec.SetField(tool.FieldType, field.TypeString, value)
	}
	if value, ok := tu.mutation.Schema(); ok {
		_spec.SetField(tool.FieldSchema, field.TypeJSON, value)
	}
	if tu.mutation.SchemaCleared() {
		_spec.ClearField(tool.FieldSchema, field.TypeJSON)
	}
	if value, ok := tu.mutation.Implementation(); ok {
		_spec.SetField(tool.FieldImplementation, field.TypeString, value)
	}
	if tu.mutation.ImplementationCleared() {
		_spec.ClearField(tool.FieldImplementation, field.TypeString)
	}
	if value, ok := tu.mutation.Version(); ok {
		_spec.SetField(tool.FieldVersion, field.TypeString, value)
	}
	if value, ok := tu.mutation.IsPublic(); ok {
		_spec.SetField(tool.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := tu.mutation.CreatedBy(); ok {
		_spec.SetField(tool.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(tool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.Tags(); ok {
		_spec.SetField(tool.FieldTags, field.TypeJSON, value)
	}
	if value, ok := tu.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tool.FieldTags, value)
		})
	}
	if tu.mutation.TagsCleared() {
		_spec.ClearField(tool.FieldTags, field.TypeJSON)
	}
	if value, ok := tu.mutation.Category(); ok {
		_spec.SetField(tool.FieldCategory, field.TypeString, value)
	}
	if tu.mutation.CategoryCleared() {
		_spec.ClearField(tool.FieldCategory, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// ToolUpdateOne is the builder for updating a single Tool entity.
type ToolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ToolMutation
}

// SetName sets the "name" field.
func (tuo *ToolUpdateOne) SetName(s string) *ToolUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *ToolUpdateOne) SetNillableName(s *string) *ToolUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// SetDescription sets the "description" field.
func (tuo *ToolUpdateOne) SetDescription(s string) *ToolUpdateOne {
	tuo.mutation.SetDescription(s)
	return tuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tuo *ToolUpdateOne) SetNillableDescription(s *string) *ToolUpdateOne {
	if s != nil {
		tuo.SetDescription(*s)
	}
	return tuo
}

// ClearDescription clears the value of the "description" field.
func (tuo *ToolUpdateOne) ClearDescription() *ToolUpdateOne {
	tuo.mutation.ClearDescription()
	return tuo
}

// SetType sets the "type" field.
func (tuo *ToolUpdateOne) SetType(s string) *ToolUpdateOne {
	tuo.mutation.SetType(s)
	return tuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tuo *ToolUpdateOne) SetNillableType(s *string) *ToolUpdateOne {
	if s != nil {
		tuo.SetType(*s)
	}
	return tuo
}

// SetSchema sets the "schema" field.
func (tuo *ToolUpdateOne) SetSchema(m map[string]interface{}) *ToolUpdateOne {
	tuo.mutation.SetSchema(m)
	return tuo
}

// ClearSchema clears the value of the "schema" field.
func (tuo *ToolUpdateOne) ClearSchema() *ToolUpdateOne {
	tuo.mutation.ClearSchema()
	return tuo
}

// SetImplementation sets the "implementation" field.
func (tuo *ToolUpdateOne) SetImplementation(s string) *ToolUpdateOne {
	tuo.mutation.SetImplementation(s)
	return tuo
}

// SetNillableImplementation sets the "implementation" field if the given value is not nil.
func (tuo *ToolUpdateOne) SetNillableImplementation(s *string) *ToolUpdateOne {
	if s != nil {
		tuo.SetImplementation(*s)
	}
	return tuo
}

// ClearImplementation clears the value of the "implementation" field.
func (tuo *ToolUpdateOne) ClearImplementation() *ToolUpdateOne {
	tuo.mutation.ClearImplementation()
	return tuo
}

// SetVersion sets the "version" field.
func (tuo *ToolUpdateOne) SetVersion(s string) *ToolUpdateOne {
	tuo.mutation.SetVersion(s)
	return tuo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (tuo *ToolUpdateOne) SetNillableVersion(s *string) *ToolUpdateOne {
	if s != nil {
		tuo.SetVersion(*s)
	}
	return tuo
}

// SetIsPublic sets the "is_public" field.
func (tuo *ToolUpdateOne) SetIsPublic(b bool) *ToolUpdateOne {
	tuo.mutation.SetIsPublic(b)
	return tuo
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (tuo *ToolUpdateOne) SetNillableIsPublic(b *bool) *ToolUpdateOne {
	if b != nil {
		tuo.SetIsPublic(*b)
	}
	return tuo
}

// SetCreatedBy sets the "created_by" field.
func (tuo *ToolUpdateOne) SetCreatedBy(s string) *ToolUpdateOne {
	tuo.mutation.SetCreatedBy(s)
	return tuo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (tuo *ToolUpdateOne) SetNillableCreatedBy(s *string) *ToolUpdateOne {
	if s != nil {
		tuo.SetCreatedBy(*s)
	}
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *ToolUpdateOne) SetUpdatedAt(t time.Time) *ToolUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetTags sets the "tags" field.
func (tuo *ToolUpdateOne) SetTags(s []string) *ToolUpdateOne {
	tuo.mutation.SetTags(s)
	return tuo
}

// AppendTags appends s to the "tags" field.
func (tuo *ToolUpdateOne) AppendTags(s []string) *ToolUpdateOne {
	tuo.mutation.AppendTags(s)
	return tuo
}

// ClearTags clears the value of the "tags" field.
func (tuo *ToolUpdateOne) ClearTags() *ToolUpdateOne {
	tuo.mutation.ClearTags()
	return tuo
}

// SetCategory sets the "category" field.
func (tuo *ToolUpdateOne) SetCategory(s string) *ToolUpdateOne {
	tuo.mutation.SetCategory(s)
	return tuo
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (tuo *ToolUpdateOne) SetNillableCategory(s *string) *ToolUpdateOne {
	if s != nil {
		tuo.SetCategory(*s)
	}
	return tuo
}

// ClearCategory clears the value of the "category" field.
func (tuo *ToolUpdateOne) ClearCategory() *ToolUpdateOne {
	tuo.mutation.ClearCategory()
	return tuo
}

// Mutation returns the ToolMutation object of the builder.
func (tuo *ToolUpdateOne) Mutation() *ToolMutation {
	return tuo.mutation
}

// Where appends a list predicates to the ToolUpdate builder.
func (tuo *ToolUpdateOne) Where(ps ...predicate.Tool) *ToolUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *ToolUpdateOne) Select(field string, fields ...string) *ToolUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Tool entity.
func (tuo *ToolUpdateOne) Save(ctx context.Context) (*Tool, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *ToolUpdateOne) SaveX(ctx context.Context) *Tool {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *ToolUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *ToolUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *ToolUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := tool.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *ToolUpdateOne) check() error {
	if v, ok := tuo.mutation.Name(); ok {
		if err := tool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tool.name": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.CreatedBy(); ok {
		if err := tool.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "Tool.created_by": %w`, err)}
		}
	}
	return nil
}

func (tuo *ToolUpdateOne) sqlSave(ctx context.Context) (_node *Tool, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tool.Table, tool.Columns, sqlgraph.NewFieldSpec(tool.FieldID, field.TypeString))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tool.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tool.FieldID)
		for _, f := range fields {
			if !tool.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(tool.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Description(); ok {
		_spec.SetField(tool.FieldDescription, field.TypeString, value)
	}
	if tuo.mutation.DescriptionCleared() {
		_spec.ClearField(tool.FieldDescription, field.TypeString)
	}
	if value, ok := tuo.mutation.GetType(); ok {
		_spec.SetField(tool.FieldType, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Schema(); ok {
		_spec.SetField(tool.FieldSchema, field.TypeJSON, value)
	}
	if tuo.mutation.SchemaCleared() {
		_spec.ClearField(tool.FieldSchema, field.TypeJSON)
	}
	if value, ok := tuo.mutation.Implementation(); ok {
		_spec.SetField(tool.FieldImplementation, field.TypeString, value)
	}
	if tuo.mutation.ImplementationCleared() {
		_spec.ClearField(tool.FieldImplementation, field.TypeString)
	}
	if value, ok := tuo.mutation.Version(); ok {
		_spec.SetField(tool.FieldVersion, field.TypeString, value)
	}
	if value, ok := tuo.mutation.IsPublic(); ok {
		_spec.SetField(tool.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := tuo.mutation.CreatedBy(); ok {
		_spec.SetField(tool.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(tool.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.Tags(); ok {
		_spec.SetField(tool.FieldTags, field.TypeJSON, value)
	}
	if value, ok := tuo.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tool.FieldTags, value)
		})
	}
	if tuo.mutation.TagsCleared() {
		_spec.ClearField(tool.FieldTags, field.TypeJSON)
	}
	if value, ok := tuo.mutation.Category(); ok {
		_spec.SetField(tool.FieldCategory, field.TypeString, value)
	}
	if tuo.mutation.CategoryCleared() {
		_spec.ClearField(tool.FieldCategory, field.TypeString)
	}
	_node = &Tool{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
