// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agent-platform/internal/model/ent/tool"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ToolCreate is the builder for creating a Tool entity.
type ToolCreate struct {
	config
	mutation *ToolMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *ToolCreate) SetName(s string) *ToolCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetDescription sets the "description" field.
func (tc *ToolCreate) SetDescription(s string) *ToolCreate {
	tc.mutation.SetDescription(s)
	return tc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tc *ToolCreate) SetNillableDescription(s *string) *ToolCreate {
	if s != nil {
		tc.SetDescription(*s)
	}
	return tc
}

// SetType sets the "type" field.
func (tc *ToolCreate) SetType(s string) *ToolCreate {
	tc.mutation.SetType(s)
	return tc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tc *ToolCreate) SetNillableType(s *string) *ToolCreate {
	if s != nil {
		tc.SetType(*s)
	}
	return tc
}

// SetSchema sets the "schema" field.
func (tc *ToolCreate) SetSchema(m map[string]interface{}) *ToolCreate {
	tc.mutation.SetSchema(m)
	return tc
}

// SetImplementation sets the "implementation" field.
func (tc *ToolCreate) SetImplementation(s string) *ToolCreate {
	tc.mutation.SetImplementation(s)
	return tc
}

// SetNillableImplementation sets the "implementation" field if the given value is not nil.
func (tc *ToolCreate) SetNillableImplementation(s *string) *ToolCreate {
	if s != nil {
		tc.SetImplementation(*s)
	}
	return tc
}

// SetVersion sets the "version" field.
func (tc *ToolCreate) SetVersion(s string) *ToolCreate {
	tc.mutation.SetVersion(s)
	return tc
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (tc *ToolCreate) SetNillableVersion(s *string) *ToolCreate {
	if s != nil {
		tc.SetVersion(*s)
	}
	return tc
}

// SetIsPublic sets the "is_public" field.
func (tc *ToolCreate) SetIsPublic(b bool) *ToolCreate {
	tc.mutation.SetIsPublic(b)
	return tc
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (tc *ToolCreate) SetNillableIsPublic(b *bool) *ToolCreate {
	if b != nil {
		tc.SetIsPublic(*b)
	}
	return tc
}

// SetCreatedBy sets the "created_by" field.
func (tc *ToolCreate) SetCreatedBy(s string) *ToolCreate {
	tc.mutation.SetCreatedBy(s)
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *ToolCreate) SetCreatedAt(t time.Time) *ToolCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *ToolCreate) SetNillableCreatedAt(t *time.Time) *ToolCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *ToolCreate) SetUpdatedAt(t time.Time) *ToolCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *ToolCreate) SetNillableUpdatedAt(t *time.Time) *ToolCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetTags sets the "tags" field.
func (tc *ToolCreate) SetTags(s []string) *ToolCreate {
	tc.mutation.SetTags(s)
	return tc
}

// SetCategory sets the "category" field.
func (tc *ToolCreate) SetCategory(s string) *ToolCreate {
	tc.mutation.SetCategory(s)
	return tc
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (tc *ToolCreate) SetNillableCategory(s *string) *ToolCreate {
	if s != nil {
		tc.SetCategory(*s)
	}
	return tc
}

// SetID sets the "id" field.
func (tc *ToolCreate) SetID(s string) *ToolCreate {
	tc.mutation.SetID(s)
	return tc
}

// Mutation returns the ToolMutation object of the builder.
func (tc *ToolCreate) Mutation() *ToolMutation {
	return tc.mutation
}

// Save creates the Tool in the database.
func (tc *ToolCreate) Save(ctx context.Context) (*Tool, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *ToolCreate) SaveX(ctx context.Context) *Tool {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *ToolCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *ToolCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *ToolCreate) defaults() {
	if _, ok := tc.mutation.GetType(); !ok {
		v := tool.DefaultType
		tc.mutation.SetType(v)
	}
	if _, ok := tc.mutation.Version(); !ok {
		v := tool.DefaultVersion
		tc.mutation.SetVersion(v)
	}
	if _, ok := tc.mutation.IsPublic(); !ok {
		v := tool.DefaultIsPublic
		tc.mutation.SetIsPublic(v)
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := tool.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := tool.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *ToolCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tool.name"`)}
	}
	if v, ok := tc.mutation.Name(); ok {
		if err := tool.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tool.name": %w`, err)}
		}
	}
	if _, ok := tc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Tool.type"`)}
	}
	if _, ok := tc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Tool.version"`)}
	}
	if _, ok := tc.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`ent: missing required field "Tool.is_public"`)}
	}
	if _, ok := tc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Tool.created_by"`)}
	}
	if v, ok := tc.mutation.CreatedBy(); ok {
		if err := tool.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "Tool.created_by": %w`, err)}
		}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Tool.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Tool.updated_at"`)}
	}
	return nil
}

func (tc *ToolCreate) sqlSave(ctx context.Context) (*Tool, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Tool.ID type: %T", _spec.ID.Value)
		}
	}
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *ToolCreate) createSpec() (*Tool, *sqlgraph.CreateSpec) {
	var (
		_node = &Tool{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(tool.Table, sqlgraph.NewFieldSpec(tool.FieldID, field.TypeString))
	)
	if id, ok := tc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(tool.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Description(); ok {
		_spec.SetField(tool.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := tc.mutation.GetType(); ok {
		_spec.SetField(tool.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := tc.mutation.Schema(); ok {
		_spec.SetField(tool.FieldSchema, field.TypeJSON, value)
		_node.Schema = value
	}
	if value, ok := tc.mutation.Implementation(); ok {
		_spec.SetField(tool.FieldImplementation, field.TypeString, value)
		_node.Implementation = value
	}
	if value, ok := tc.mutation.Version(); ok {
		_spec.SetField(tool.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := tc.mutation.IsPublic(); ok {
		_spec.SetField(tool.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if value, ok := tc.mutation.CreatedBy(); ok {
		_spec.SetField(tool.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(tool.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(tool.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := tc.mutation.Tags(); ok {
		_spec.SetField(tool.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := tc.mutation.Category(); ok {
		_spec.SetField(tool.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	return _node, _spec
}

// ToolCreateBulk is the builder for creating many Tool entities in bulk.
type ToolCreateBulk struct {
	config
	err      error
	builders []*ToolCreate
}

// Save creates the Tool entities in the database.
func (tcb *ToolCreateBulk) Save(ctx context.Context) ([]*Tool, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Tool, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ToolMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *ToolCreateBulk) SaveX(ctx context.Context) []*Tool {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *ToolCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *ToolCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
