// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agent-platform/internal/model/ent/predicate"
	"agent-platform/internal/model/ent/workflowexecution"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkflowExecutionUpdate is the builder for updating WorkflowExecution entities.
type WorkflowExecutionUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowExecutionMutation
}

// Where appends a list predicates to the WorkflowExecutionUpdate builder.
func (weu *WorkflowExecutionUpdate) Where(ps ...predicate.WorkflowExecution) *WorkflowExecutionUpdate {
	weu.mutation.Where(ps...)
	return weu
}

// SetWorkflowID sets the "workflow_id" field.
func (weu *WorkflowExecutionUpdate) SetWorkflowID(s string) *WorkflowExecutionUpdate {
	weu.mutation.SetWorkflowID(s)
	return weu
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (weu *WorkflowExecutionUpdate) SetNillableWorkflowID(s *string) *WorkflowExecutionUpdate {
	if s != nil {
		weu.SetWorkflowID(*s)
	}
	return weu
}

// SetInput sets the "input" field.
func (weu *WorkflowExecutionUpdate) SetInput(m map[string]interface{}) *WorkflowExecutionUpdate {
	weu.mutation.SetInput(m)
	return weu
}

// ClearInput clears the value of the "input" field.
func (weu *WorkflowExecutionUpdate) ClearInput() *WorkflowExecutionUpdate {
	weu.mutation.ClearInput()
	return weu
}

// SetOutput sets the "output" field.
func (weu *WorkflowExecutionUpdate) SetOutput(m map[string]interface{}) *WorkflowExecutionUpdate {
	weu.mutation.SetOutput(m)
	return weu
}

// ClearOutput clears the value of the "output" field.
func (weu *WorkflowExecutionUpdate) ClearOutput() *WorkflowExecutionUpdate {
	weu.mutation.ClearOutput()
	return weu
}

// SetContext sets the "context" field.
func (weu *WorkflowExecutionUpdate) SetContext(m map[string]interface{}) *WorkflowExecutionUpdate {
	weu.mutation.SetContext(m)
	return weu
}

// ClearContext clears the value of the "context" field.
func (weu *WorkflowExecutionUpdate) ClearContext() *WorkflowExecutionUpdate {
	weu.mutation.ClearContext()
	return weu
}

// SetStatus sets the "status" field.
func (weu *WorkflowExecutionUpdate) SetStatus(s string) *WorkflowExecutionUpdate {
	weu.mutation.SetStatus(s)
	return weu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (weu *WorkflowExecutionUpdate) SetNillableStatus(s *string) *WorkflowExecutionUpdate {
	if s != nil {
		weu.SetStatus(*s)
	}
	return weu
}

// SetCurrentStep sets the "current_step" field.
func (weu *WorkflowExecutionUpdate) SetCurrentStep(s string) *WorkflowExecutionUpdate {
	weu.mutation.SetCurrentStep(s)
	return weu
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (weu *WorkflowExecutionUpdate) SetNillableCurrentStep(s *string) *WorkflowExecutionUpdate {
	if s != nil {
		weu.SetCurrentStep(*s)
	}
	return weu
}

// ClearCurrentStep clears the value of the "current_step" field.
func (weu *WorkflowExecutionUpdate) ClearCurrentStep() *WorkflowExecutionUpdate {
	weu.mutation.ClearCurrentStep()
	return weu
}

// SetError sets the "error" field.
func (weu *WorkflowExecutionUpdate) SetError(s string) *WorkflowExecutionUpdate {
	weu.mutation.SetError(s)
	return weu
}

// SetNillableError sets the "error" field if the given value is not nil.
func (weu *WorkflowExecutionUpdate) SetNillableError(s *string) *WorkflowExecutionUpdate {
	if s != nil {
		weu.SetError(*s)
	}
	return weu
}

// ClearError clears the value of the "error" field.
func (weu *WorkflowExecutionUpdate) ClearError() *WorkflowExecutionUpdate {
	weu.mutation.ClearError()
	return weu
}

// SetStartedBy sets the "started_by" field.
func (weu *WorkflowExecutionUpdate) SetStartedBy(s string) *WorkflowExecutionUpdate {
	weu.mutation.SetStartedBy(s)
	return weu
}

// SetNillableStartedBy sets the "started_by" field if the given value is not nil.
func (weu *WorkflowExecutionUpdate) SetNillableStartedBy(s *string) *WorkflowExecutionUpdate {
	if s != nil {
		weu.SetStartedBy(*s)
	}
	return weu
}

// SetStartedAt sets the "started_at" field.
func (weu *WorkflowExecutionUpdate) SetStartedAt(t time.Time) *WorkflowExecutionUpdate {
	weu.mutation.SetStartedAt(t)
	return weu
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (weu *WorkflowExecutionUpdate) SetNillableStartedAt(t *time.Time) *WorkflowExecutionUpdate {
	if t != nil {
		weu.SetStartedAt(*t)
	}
	return weu
}

// SetCompletedAt sets the "completed_at" field.
func (weu *WorkflowExecutionUpdate) SetCompletedAt(t time.Time) *WorkflowExecutionUpdate {
	weu.mutation.SetCompletedAt(t)
	return weu
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (weu *WorkflowExecutionUpdate) SetNillableCompletedAt(t *time.Time) *WorkflowExecutionUpdate {
	if t != nil {
		weu.SetCompletedAt(*t)
	}
	return weu
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (weu *WorkflowExecutionUpdate) ClearCompletedAt() *WorkflowExecutionUpdate {
	weu.mutation.ClearCompletedAt()
	return weu
}

// SetUpdatedAt sets the "updated_at" field.
func (weu *WorkflowExecutionUpdate) SetUpdatedAt(t time.Time) *WorkflowExecutionUpdate {
	weu.mutation.SetUpdatedAt(t)
	return weu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (weu *WorkflowExecutionUpdate) SetNillableUpdatedAt(t *time.Time) *WorkflowExecutionUpdate {
	if t != nil {
		weu.SetUpdatedAt(*t)
	}
	return weu
}

// Mutation returns the WorkflowExecutionMutation object of the builder.
func (weu *WorkflowExecutionUpdate) Mutation() *WorkflowExecutionMutation {
	return weu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (weu *WorkflowExecutionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, weu.sqlSave, weu.mutation, weu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (weu *WorkflowExecutionUpdate) SaveX(ctx context.Context) int {
	affected, err := weu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (weu *WorkflowExecutionUpdate) Exec(ctx context.Context) error {
	_, err := weu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (weu *WorkflowExecutionUpdate) ExecX(ctx context.Context) {
	if err := weu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (weu *WorkflowExecutionUpdate) check() error {
	if v, ok := weu.mutation.WorkflowID(); ok {
		if err := workflowexecution.WorkflowIDValidator(v); err != nil {
			return &ValidationError{Name: "workflow_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowExecution.workflow_id": %w`, err)}
		}
	}
	if v, ok := weu.mutation.StartedBy(); ok {
		if err := workflowexecution.StartedByValidator(v); err != nil {
			return &ValidationError{Name: "started_by", err: fmt.Errorf(`ent: validator failed for field "WorkflowExecution.started_by": %w`, err)}
		}
	}
	return nil
}

func (weu *WorkflowExecutionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := weu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowexecution.Table, workflowexecution.Columns, sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeString))
	if ps := weu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := weu.mutation.WorkflowID(); ok {
		_spec.SetField(workflowexecution.FieldWorkflowID, field.TypeString, value)
	}
	if value, ok := weu.mutation.Input(); ok {
		_spec.SetField(workflowexecution.FieldInput, field.TypeJSON, value)
	}
	if weu.mutation.InputCleared() {
		_spec.ClearField(workflowexecution.FieldInput, field.TypeJSON)
	}
	if value, ok := weu.mutation.Output(); ok {
		_spec.SetField(workflowexecution.FieldOutput, field.TypeJSON, value)
	}
	if weu.mutation.OutputCleared() {
		_spec.ClearField(workflowexecution.FieldOutput, field.TypeJSON)
	}
	if value, ok := weu.mutation.Context(); ok {
		_spec.SetField(workflowexecution.FieldContext, field.TypeJSON, value)
	}
	if weu.mutation.ContextCleared() {
		_spec.ClearField(workflowexecution.FieldContext, field.TypeJSON)
	}
	if value, ok := weu.mutation.Status(); ok {
		_spec.SetField(workflowexecution.FieldStatus, field.TypeString, value)
	}
	if value, ok := weu.mutation.CurrentStep(); ok {
		_spec.SetField(workflowexecution.FieldCurrentStep, field.TypeString, value)
	}
	if weu.mutation.CurrentStepCleared() {
		_spec.ClearField(workflowexecution.FieldCurrentStep, field.TypeString)
	}
	if value, ok := weu.mutation.Error(); ok {
		_spec.SetField(workflowexecution.FieldError, field.TypeString, value)
	}
	if weu.mutation.ErrorCleared() {
		_spec.ClearField(workflowexecution.FieldError, field.TypeString)
	}
	if value, ok := weu.mutation.StartedBy(); ok {
		_spec.SetField(workflowexecution.FieldStartedBy, field.TypeString, value)
	}
	if value, ok := weu.mutation.StartedAt(); ok {
		_spec.SetField(workflowexecution.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := weu.mutation.CompletedAt(); ok {
		_spec.SetField(workflowexecution.FieldCompletedAt, field.TypeTime, value)
	}
	if weu.mutation.CompletedAtCleared() {
		_spec.ClearField(workflowexecution.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := weu.mutation.UpdatedAt(); ok {
		_spec.SetField(workflowexecution.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, weu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowexecution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	weu.mutation.done = true
	return n, nil
}

// WorkflowExecutionUpdateOne is the builder for updating a single WorkflowExecution entity.
type WorkflowExecutionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowExecutionMutation
}

// SetWorkflowID sets the "workflow_id" field.
func (weuo *WorkflowExecutionUpdateOne) SetWorkflowID(s string) *WorkflowExecutionUpdateOne {
	weuo.mutation.SetWorkflowID(s)
	return weuo
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (weuo *WorkflowExecutionUpdateOne) SetNillableWorkflowID(s *string) *WorkflowExecutionUpdateOne {
	if s != nil {
		weuo.SetWorkflowID(*s)
	}
	return weuo
}

// SetInput sets the "input" field.
func (weuo *WorkflowExecutionUpdateOne) SetInput(m map[string]interface{}) *WorkflowExecutionUpdateOne {
	weuo.mutation.SetInput(m)
	return weuo
}

// ClearInput clears the value of the "input" field.
func (weuo *WorkflowExecutionUpdateOne) ClearInput() *WorkflowExecutionUpdateOne {
	weuo.mutation.ClearInput()
	return weuo
}

// SetOutput sets the "output" field.
func (weuo *WorkflowExecutionUpdateOne) SetOutput(m map[string]interface{}) *WorkflowExecutionUpdateOne {
	weuo.mutation.SetOutput(m)
	return weuo
}

// ClearOutput clears the value of the "output" field.
func (weuo *WorkflowExecutionUpdateOne) ClearOutput() *WorkflowExecutionUpdateOne {
	weuo.mutation.ClearOutput()
	return weuo
}

// SetContext sets the "context" field.
func (weuo *WorkflowExecutionUpdateOne) SetContext(m map[string]interface{}) *WorkflowExecutionUpdateOne {
	weuo.mutation.SetContext(m)
	return weuo
}

// ClearContext clears the value of the "context" field.
func (weuo *WorkflowExecutionUpdateOne) ClearContext() *WorkflowExecutionUpdateOne {
	weuo.mutation.ClearContext()
	return weuo
}

// SetStatus sets the "status" field.
func (weuo *WorkflowExecutionUpdateOne) SetStatus(s string) *WorkflowExecutionUpdateOne {
	weuo.mutation.SetStatus(s)
	return weuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (weuo *WorkflowExecutionUpdateOne) SetNillableStatus(s *string) *WorkflowExecutionUpdateOne {
	if s != nil {
		weuo.SetStatus(*s)
	}
	return weuo
}

// SetCurrentStep sets the "current_step" field.
func (weuo *WorkflowExecutionUpdateOne) SetCurrentStep(s string) *WorkflowExecutionUpdateOne {
	weuo.mutation.SetCurrentStep(s)
	return weuo
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (weuo *WorkflowExecutionUpdateOne) SetNillableCurrentStep(s *string) *WorkflowExecutionUpdateOne {
	if s != nil {
		weuo.SetCurrentStep(*s)
	}
	return weuo
}

// ClearCurrentStep clears the value of the "current_step" field.
func (weuo *WorkflowExecutionUpdateOne) ClearCurrentStep() *WorkflowExecutionUpdateOne {
	weuo.mutation.ClearCurrentStep()
	return weuo
}

// SetError sets the "error" field.
func (weuo *WorkflowExecutionUpdateOne) SetError(s string) *WorkflowExecutionUpdateOne {
	weuo.mutation.SetError(s)
	return weuo
}

// SetNillableError sets the "error" field if the given value is not nil.
func (weuo *WorkflowExecutionUpdateOne) SetNillableError(s *string) *WorkflowExecutionUpdateOne {
	if s != nil {
		weuo.SetError(*s)
	}
	return weuo
}

// ClearError clears the value of the "error" field.
func (weuo *WorkflowExecutionUpdateOne) ClearError() *WorkflowExecutionUpdateOne {
	weuo.mutation.ClearError()
	return weuo
}

// SetStartedBy sets the "started_by" field.
func (weuo *WorkflowExecutionUpdateOne) SetStartedBy(s string) *WorkflowExecutionUpdateOne {
	weuo.mutation.SetStartedBy(s)
	return weuo
}

// SetNillableStartedBy sets the "started_by" field if the given value is not nil.
func (weuo *WorkflowExecutionUpdateOne) SetNillableStartedBy(s *string) *WorkflowExecutionUpdateOne {
	if s != nil {
		weuo.SetStartedBy(*s)
	}
	return weuo
}

// SetStartedAt sets the "started_at" field.
func (weuo *WorkflowExecutionUpdateOne) SetStartedAt(t time.Time) *WorkflowExecutionUpdateOne {
	weuo.mutation.SetStartedAt(t)
	return weuo
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (weuo *WorkflowExecutionUpdateOne) SetNillableStartedAt(t *time.Time) *WorkflowExecutionUpdateOne {
	if t != nil {
		weuo.SetStartedAt(*t)
	}
	return weuo
}

// SetCompletedAt sets the "completed_at" field.
func (weuo *WorkflowExecutionUpdateOne) SetCompletedAt(t time.Time) *WorkflowExecutionUpdateOne {
	weuo.mutation.SetCompletedAt(t)
	return weuo
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (weuo *WorkflowExecutionUpdateOne) SetNillableCompletedAt(t *time.Time) *WorkflowExecutionUpdateOne {
	if t != nil {
		weuo.SetCompletedAt(*t)
	}
	return weuo
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (weuo *WorkflowExecutionUpdateOne) ClearCompletedAt() *WorkflowExecutionUpdateOne {
	weuo.mutation.ClearCompletedAt()
	return weuo
}

// SetUpdatedAt sets the "updated_at" field.
func (weuo *WorkflowExecutionUpdateOne) SetUpdatedAt(t time.Time) *WorkflowExecutionUpdateOne {
	weuo.mutation.SetUpdatedAt(t)
	return weuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (weuo *WorkflowExecutionUpdateOne) SetNillableUpdatedAt(t *time.Time) *WorkflowExecutionUpdateOne {
	if t != nil {
		weuo.SetUpdatedAt(*t)
	}
	return weuo
}

// Mutation returns the WorkflowExecutionMutation object of the builder.
func (weuo *WorkflowExecutionUpdateOne) Mutation() *WorkflowExecutionMutation {
	return weuo.mutation
}

// Where appends a list predicates to the WorkflowExecutionUpdate builder.
func (weuo *WorkflowExecutionUpdateOne) Where(ps ...predicate.WorkflowExecution) *WorkflowExecutionUpdateOne {
	weuo.mutation.Where(ps...)
	return weuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (weuo *WorkflowExecutionUpdateOne) Select(field string, fields ...string) *WorkflowExecutionUpdateOne {
	weuo.fields = append([]string{field}, fields...)
	return weuo
}

// Save executes the query and returns the updated WorkflowExecution entity.
func (weuo *WorkflowExecutionUpdateOne) Save(ctx context.Context) (*WorkflowExecution, error) {
	return withHooks(ctx, weuo.sqlSave, weuo.mutation, weuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (weuo *WorkflowExecutionUpdateOne) SaveX(ctx context.Context) *WorkflowExecution {
	node, err := weuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (weuo *WorkflowExecutionUpdateOne) Exec(ctx context.Context) error {
	_, err := weuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (weuo *WorkflowExecutionUpdateOne) ExecX(ctx context.Context) {
	if err := weuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (weuo *WorkflowExecutionUpdateOne) check() error {
	if v, ok := weuo.mutation.WorkflowID(); ok {
		if err := workflowexecution.WorkflowIDValidator(v); err != nil {
			return &ValidationError{Name: "workflow_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowExecution.workflow_id": %w`, err)}
		}
	}
	if v, ok := weuo.mutation.StartedBy(); ok {
		if err := workflowexecution.StartedByValidator(v); err != nil {
			return &ValidationError{Name: "started_by", err: fmt.Errorf(`ent: validator failed for field "WorkflowExecution.started_by": %w`, err)}
		}
	}
	return nil
}

func (weuo *WorkflowExecutionUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowExecution, err error) {
	if err := weuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowexecution.Table, workflowexecution.Columns, sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeString))
	id, ok := weuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowExecution.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := weuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowexecution.FieldID)
		for _, f := range fields {
			if !workflowexecution.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowexecution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := weuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := weuo.mutation.WorkflowID(); ok {
		_spec.SetField(workflowexecution.FieldWorkflowID, field.TypeString, value)
	}
	if value, ok := weuo.mutation.Input(); ok {
		_spec.SetField(workflowexecution.FieldInput, field.TypeJSON, value)
	}
	if weuo.mutation.InputCleared() {
		_spec.ClearField(workflowexecution.FieldInput, field.TypeJSON)
	}
	if value, ok := weuo.mutation.Output(); ok {
		_spec.SetField(workflowexecution.FieldOutput, field.TypeJSON, value)
	}
	if weuo.mutation.OutputCleared() {
		_spec.ClearField(workflowexecution.FieldOutput, field.TypeJSON)
	}
	if value, ok := weuo.mutation.Context(); ok {
		_spec.SetField(workflowexecution.FieldContext, field.TypeJSON, value)
	}
	if weuo.mutation.ContextCleared() {
		_spec.ClearField(workflowexecution.FieldContext, field.TypeJSON)
	}
	if value, ok := weuo.mutation.Status(); ok {
		_spec.SetField(workflowexecution.FieldStatus, field.TypeString, value)
	}
	if value, ok := weuo.mutation.CurrentStep(); ok {
		_spec.SetField(workflowexecution.FieldCurrentStep, field.TypeString, value)
	}
	if weuo.mutation.CurrentStepCleared() {
		_spec.ClearField(workflowexecution.FieldCurrentStep, field.TypeString)
	}
	if value, ok := weuo.mutation.Error(); ok {
		_spec.SetField(workflowexecution.FieldError, field.TypeString, value)
	}
	if weuo.mutation.ErrorCleared() {
		_spec.ClearField(workflowexecution.FieldError, field.TypeString)
	}
	if value, ok := weuo.mutation.StartedBy(); ok {
		_spec.SetField(workflowexecution.FieldStartedBy, field.TypeString, value)
	}
	if value, ok := weuo.mutation.StartedAt(); ok {
		_spec.SetField(workflowexecution.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := weuo.mutation.CompletedAt(); ok {
		_spec.SetField(workflowexecution.FieldCompletedAt, field.TypeTime, value)
	}
	if weuo.mutation.CompletedAtCleared() {
		_spec.ClearField(workflowexecution.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := weuo.mutation.UpdatedAt(); ok {
		_spec.SetField(workflowexecution.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &WorkflowExecution{config: weuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, weuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowexecution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	weuo.mutation.done = true
	return _node, nil
}
