// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agent-platform/internal/model/ent/workflowexecution"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkflowExecutionCreate is the builder for creating a WorkflowExecution entity.
type WorkflowExecutionCreate struct {
	config
	mutation *WorkflowExecutionMutation
	hooks    []Hook
}

// SetWorkflowID sets the "workflow_id" field.
func (wec *WorkflowExecutionCreate) SetWorkflowID(s string) *WorkflowExecutionCreate {
	wec.mutation.SetWorkflowID(s)
	return wec
}

// SetInput sets the "input" field.
func (wec *WorkflowExecutionCreate) SetInput(m map[string]interface{}) *WorkflowExecutionCreate {
	wec.mutation.SetInput(m)
	return wec
}

// SetOutput sets the "output" field.
func (wec *WorkflowExecutionCreate) SetOutput(m map[string]interface{}) *WorkflowExecutionCreate {
	wec.mutation.SetOutput(m)
	return wec
}

// SetContext sets the "context" field.
func (wec *WorkflowExecutionCreate) SetContext(m map[string]interface{}) *WorkflowExecutionCreate {
	wec.mutation.SetContext(m)
	return wec
}

// SetStatus sets the "status" field.
func (wec *WorkflowExecutionCreate) SetStatus(s string) *WorkflowExecutionCreate {
	wec.mutation.SetStatus(s)
	return wec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wec *WorkflowExecutionCreate) SetNillableStatus(s *string) *WorkflowExecutionCreate {
	if s != nil {
		wec.SetStatus(*s)
	}
	return wec
}

// SetCurrentStep sets the "current_step" field.
func (wec *WorkflowExecutionCreate) SetCurrentStep(s string) *WorkflowExecutionCreate {
	wec.mutation.SetCurrentStep(s)
	return wec
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (wec *WorkflowExecutionCreate) SetNillableCurrentStep(s *string) *WorkflowExecutionCreate {
	if s != nil {
		wec.SetCurrentStep(*s)
	}
	return wec
}

// SetError sets the "error" field.
func (wec *WorkflowExecutionCreate) SetError(s string) *WorkflowExecutionCreate {
	wec.mutation.SetError(s)
	return wec
}

// SetNillableError sets the "error" field if the given value is not nil.
func (wec *WorkflowExecutionCreate) SetNillableError(s *string) *WorkflowExecutionCreate {
	if s != nil {
		wec.SetError(*s)
	}
	return wec
}

// SetStartedBy sets the "started_by" field.
func (wec *WorkflowExecutionCreate) SetStartedBy(s string) *WorkflowExecutionCreate {
	wec.mutation.SetStartedBy(s)
	return wec
}

// SetStartedAt sets the "started_at" field.
func (wec *WorkflowExecutionCreate) SetStartedAt(t time.Time) *WorkflowExecutionCreate {
	wec.mutation.SetStartedAt(t)
	return wec
}

// SetCompletedAt sets the "completed_at" field.
func (wec *WorkflowExecutionCreate) SetCompletedAt(t time.Time) *WorkflowExecutionCreate {
	wec.mutation.SetCompletedAt(t)
	return wec
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (wec *WorkflowExecutionCreate) SetNillableCompletedAt(t *time.Time) *WorkflowExecutionCreate {
	if t != nil {
		wec.SetCompletedAt(*t)
	}
	return wec
}

// SetUpdatedAt sets the "updated_at" field.
func (wec *WorkflowExecutionCreate) SetUpdatedAt(t time.Time) *WorkflowExecutionCreate {
	wec.mutation.SetUpdatedAt(t)
	return wec
}

// SetID sets the "id" field.
func (wec *WorkflowExecutionCreate) SetID(s string) *WorkflowExecutionCreate {
	wec.mutation.SetID(s)
	return wec
}

// Mutation returns the WorkflowExecutionMutation object of the builder.
func (wec *WorkflowExecutionCreate) Mutation() *WorkflowExecutionMutation {
	return wec.mutation
}

// Save creates the WorkflowExecution in the database.
func (wec *WorkflowExecutionCreate) Save(ctx context.Context) (*WorkflowExecution, error) {
	wec.defaults()
	return withHooks(ctx, wec.sqlSave, wec.mutation, wec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wec *WorkflowExecutionCreate) SaveX(ctx context.Context) *WorkflowExecution {
	v, err := wec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wec *WorkflowExecutionCreate) Exec(ctx context.Context) error {
	_, err := wec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wec *WorkflowExecutionCreate) ExecX(ctx context.Context) {
	if err := wec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wec *WorkflowExecutionCreate) defaults() {
	if _, ok := wec.mutation.Status(); !ok {
		v := workflowexecution.DefaultStatus
		wec.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wec *WorkflowExecutionCreate) check() error {
	if _, ok := wec.mutation.WorkflowID(); !ok {
		return &ValidationError{Name: "workflow_id", err: errors.New(`ent: missing required field "WorkflowExecution.workflow_id"`)}
	}
	if v, ok := wec.mutation.WorkflowID(); ok {
		if err := workflowexecution.WorkflowIDValidator(v); err != nil {
			return &ValidationError{Name: "workflow_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowExecution.workflow_id": %w`, err)}
		}
	}
	if _, ok := wec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WorkflowExecution.status"`)}
	}
	if _, ok := wec.mutation.StartedBy(); !ok {
		return &ValidationError{Name: "started_by", err: errors.New(`ent: missing required field "WorkflowExecution.started_by"`)}
	}
	if v, ok := wec.mutation.StartedBy(); ok {
		if err := workflowexecution.StartedByValidator(v); err != nil {
			return &ValidationError{Name: "started_by", err: fmt.Errorf(`ent: validator failed for field "WorkflowExecution.started_by": %w`, err)}
		}
	}
	if _, ok := wec.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "WorkflowExecution.started_at"`)}
	}
	if _, ok := wec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WorkflowExecution.updated_at"`)}
	}
	return nil
}

func (wec *WorkflowExecutionCreate) sqlSave(ctx context.Context) (*WorkflowExecution, error) {
	if err := wec.check(); err != nil {
		return nil, err
	}
	_node, _spec := wec.createSpec()
	if err := sqlgraph.CreateNode(ctx, wec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected WorkflowExecution.ID type: %T", _spec.ID.Value)
		}
	}
	wec.mutation.id = &_node.ID
	wec.mutation.done = true
	return _node, nil
}

func (wec *WorkflowExecutionCreate) createSpec() (*WorkflowExecution, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkflowExecution{config: wec.config}
		_spec = sqlgraph.NewCreateSpec(workflowexecution.Table, sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeString))
	)
	if id, ok := wec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := wec.mutation.WorkflowID(); ok {
		_spec.SetField(workflowexecution.FieldWorkflowID, field.TypeString, value)
		_node.WorkflowID = value
	}
	if value, ok := wec.mutation.Input(); ok {
		_spec.SetField(workflowexecution.FieldInput, field.TypeJSON, value)
		_node.Input = value
	}
	if value, ok := wec.mutation.Output(); ok {
		_spec.SetField(workflowexecution.FieldOutput, field.TypeJSON, value)
		_node.Output = value
	}
	if value, ok := wec.mutation.Context(); ok {
		_spec.SetField(workflowexecution.FieldContext, field.TypeJSON, value)
		_node.Context = value
	}
	if value, ok := wec.mutation.Status(); ok {
		_spec.SetField(workflowexecution.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := wec.mutation.CurrentStep(); ok {
		_spec.SetField(workflowexecution.FieldCurrentStep, field.TypeString, value)
		_node.CurrentStep = value
	}
	if value, ok := wec.mutation.Error(); ok {
		_spec.SetField(workflowexecution.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := wec.mutation.StartedBy(); ok {
		_spec.SetField(workflowexecution.FieldStartedBy, field.TypeString, value)
		_node.StartedBy = value
	}
	if value, ok := wec.mutation.StartedAt(); ok {
		_spec.SetField(workflowexecution.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := wec.mutation.CompletedAt(); ok {
		_spec.SetField(workflowexecution.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = value
	}
	if value, ok := wec.mutation.UpdatedAt(); ok {
		_spec.SetField(workflowexecution.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// WorkflowExecutionCreateBulk is the builder for creating many WorkflowExecution entities in bulk.
type WorkflowExecutionCreateBulk struct {
	config
	err      error
	builders []*WorkflowExecutionCreate
}

// Save creates the WorkflowExecution entities in the database.
func (wecb *WorkflowExecutionCreateBulk) Save(ctx context.Context) ([]*WorkflowExecution, error) {
	if wecb.err != nil {
		return nil, wecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(wecb.builders))
	nodes := make([]*WorkflowExecution, len(wecb.builders))
	mutators := make([]Mutator, len(wecb.builders))
	for i := range wecb.builders {
		func(i int, root context.Context) {
			builder := wecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkflowExecutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wecb *WorkflowExecutionCreateBulk) SaveX(ctx context.Context) []*WorkflowExecution {
	v, err := wecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wecb *WorkflowExecutionCreateBulk) Exec(ctx context.Context) error {
	_, err := wecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wecb *WorkflowExecutionCreateBulk) ExecX(ctx context.Context) {
	if err := wecb.Exec(ctx); err != nil {
		panic(err)
	}
}
