// Code generated by ent, DO NOT EDIT.

package documentchunk

import (
	"agent-platform/internal/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldContainsFold(FieldID, id))
}

// KnowledgeBaseID applies equality check predicate on the "knowledge_base_id" field. It's identical to KnowledgeBaseIDEQ.
func KnowledgeBaseID(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldKnowledgeBaseID, v))
}

// DocumentID applies equality check predicate on the "document_id" field. It's identical to DocumentIDEQ.
func DocumentID(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldDocumentID, v))
}

// ChunkIndex applies equality check predicate on the "chunk_index" field. It's identical to ChunkIndexEQ.
func ChunkIndex(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldChunkIndex, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldCreatedAt, v))
}

// KnowledgeBaseIDEQ applies the EQ predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDEQ(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDNEQ applies the NEQ predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDNEQ(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDIn applies the In predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDIn(vs ...string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldKnowledgeBaseID, vs...))
}

// KnowledgeBaseIDNotIn applies the NotIn predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDNotIn(vs ...string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldKnowledgeBaseID, vs...))
}

// KnowledgeBaseIDGT applies the GT predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDGT(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGT(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDGTE applies the GTE predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDGTE(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGTE(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDLT applies the LT predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDLT(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLT(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDLTE applies the LTE predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDLTE(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLTE(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDContains applies the Contains predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDContains(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldContains(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDHasPrefix applies the HasPrefix predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDHasPrefix(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldHasPrefix(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDHasSuffix applies the HasSuffix predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDHasSuffix(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldHasSuffix(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDEqualFold applies the EqualFold predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDEqualFold(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEqualFold(FieldKnowledgeBaseID, v))
}

// KnowledgeBaseIDContainsFold applies the ContainsFold predicate on the "knowledge_base_id" field.
func KnowledgeBaseIDContainsFold(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldContainsFold(FieldKnowledgeBaseID, v))
}

// DocumentIDEQ applies the EQ predicate on the "document_id" field.
func DocumentIDEQ(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldDocumentID, v))
}

// DocumentIDNEQ applies the NEQ predicate on the "document_id" field.
func DocumentIDNEQ(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldDocumentID, v))
}

// DocumentIDIn applies the In predicate on the "document_id" field.
func DocumentIDIn(vs ...string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldDocumentID, vs...))
}

// DocumentIDNotIn applies the NotIn predicate on the "document_id" field.
func DocumentIDNotIn(vs ...string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldDocumentID, vs...))
}

// DocumentIDGT applies the GT predicate on the "document_id" field.
func DocumentIDGT(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGT(FieldDocumentID, v))
}

// DocumentIDGTE applies the GTE predicate on the "document_id" field.
func DocumentIDGTE(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGTE(FieldDocumentID, v))
}

// DocumentIDLT applies the LT predicate on the "document_id" field.
func DocumentIDLT(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLT(FieldDocumentID, v))
}

// DocumentIDLTE applies the LTE predicate on the "document_id" field.
func DocumentIDLTE(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLTE(FieldDocumentID, v))
}

// DocumentIDContains applies the Contains predicate on the "document_id" field.
func DocumentIDContains(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldContains(FieldDocumentID, v))
}

// DocumentIDHasPrefix applies the HasPrefix predicate on the "document_id" field.
func DocumentIDHasPrefix(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldHasPrefix(FieldDocumentID, v))
}

// DocumentIDHasSuffix applies the HasSuffix predicate on the "document_id" field.
func DocumentIDHasSuffix(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldHasSuffix(FieldDocumentID, v))
}

// DocumentIDEqualFold applies the EqualFold predicate on the "document_id" field.
func DocumentIDEqualFold(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEqualFold(FieldDocumentID, v))
}

// DocumentIDContainsFold applies the ContainsFold predicate on the "document_id" field.
func DocumentIDContainsFold(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldContainsFold(FieldDocumentID, v))
}

// ChunkIndexEQ applies the EQ predicate on the "chunk_index" field.
func ChunkIndexEQ(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldChunkIndex, v))
}

// ChunkIndexNEQ applies the NEQ predicate on the "chunk_index" field.
func ChunkIndexNEQ(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldChunkIndex, v))
}

// ChunkIndexIn applies the In predicate on the "chunk_index" field.
func ChunkIndexIn(vs ...int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldChunkIndex, vs...))
}

// ChunkIndexNotIn applies the NotIn predicate on the "chunk_index" field.
func ChunkIndexNotIn(vs ...int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldChunkIndex, vs...))
}

// ChunkIndexGT applies the GT predicate on the "chunk_index" field.
func ChunkIndexGT(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGT(FieldChunkIndex, v))
}

// ChunkIndexGTE applies the GTE predicate on the "chunk_index" field.
func ChunkIndexGTE(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGTE(FieldChunkIndex, v))
}

// ChunkIndexLT applies the LT predicate on the "chunk_index" field.
func ChunkIndexLT(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLT(FieldChunkIndex, v))
}

// ChunkIndexLTE applies the LTE predicate on the "chunk_index" field.
func ChunkIndexLTE(v int) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLTE(FieldChunkIndex, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldContainsFold(FieldContent, v))
}

// EmbeddingIsNil applies the IsNil predicate on the "embedding" field.
func EmbeddingIsNil() predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIsNull(FieldEmbedding))
}

// EmbeddingNotNil applies the NotNil predicate on the "embedding" field.
func EmbeddingNotNil() predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotNull(FieldEmbedding))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DocumentChunk) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DocumentChunk) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DocumentChunk) predicate.DocumentChunk {
	return predicate.DocumentChunk(sql.NotPredicates(p))
}
