/**
 * @fileoverview gRPC-Web generated client stub for api
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.1
// source: agent.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as agent_pb from './agent_pb'; // proto import: "agent.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class AgentServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateAgent = new grpcWeb.MethodDescriptor(
    '/api.AgentService/CreateAgent',
    grpcWeb.MethodType.UNARY,
    agent_pb.CreateAgentRequest,
    agent_pb.Agent,
    (request: agent_pb.CreateAgentRequest) => {
      return request.serializeBinary();
    },
    agent_pb.Agent.deserializeBinary
  );

  createAgent(
    request: agent_pb.CreateAgentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<agent_pb.Agent>;

  createAgent(
    request: agent_pb.CreateAgentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: agent_pb.Agent) => void): grpcWeb.ClientReadableStream<agent_pb.Agent>;

  createAgent(
    request: agent_pb.CreateAgentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: agent_pb.Agent) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.AgentService/CreateAgent',
        request,
        metadata || {},
        this.methodDescriptorCreateAgent,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.AgentService/CreateAgent',
    request,
    metadata || {},
    this.methodDescriptorCreateAgent);
  }

  methodDescriptorListAgents = new grpcWeb.MethodDescriptor(
    '/api.AgentService/ListAgents',
    grpcWeb.MethodType.UNARY,
    agent_pb.ListAgentsRequest,
    agent_pb.ListAgentsResponse,
    (request: agent_pb.ListAgentsRequest) => {
      return request.serializeBinary();
    },
    agent_pb.ListAgentsResponse.deserializeBinary
  );

  listAgents(
    request: agent_pb.ListAgentsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<agent_pb.ListAgentsResponse>;

  listAgents(
    request: agent_pb.ListAgentsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: agent_pb.ListAgentsResponse) => void): grpcWeb.ClientReadableStream<agent_pb.ListAgentsResponse>;

  listAgents(
    request: agent_pb.ListAgentsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: agent_pb.ListAgentsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.AgentService/ListAgents',
        request,
        metadata || {},
        this.methodDescriptorListAgents,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.AgentService/ListAgents',
    request,
    metadata || {},
    this.methodDescriptorListAgents);
  }

  methodDescriptorGetAgent = new grpcWeb.MethodDescriptor(
    '/api.AgentService/GetAgent',
    grpcWeb.MethodType.UNARY,
    agent_pb.GetAgentRequest,
    agent_pb.Agent,
    (request: agent_pb.GetAgentRequest) => {
      return request.serializeBinary();
    },
    agent_pb.Agent.deserializeBinary
  );

  getAgent(
    request: agent_pb.GetAgentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<agent_pb.Agent>;

  getAgent(
    request: agent_pb.GetAgentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: agent_pb.Agent) => void): grpcWeb.ClientReadableStream<agent_pb.Agent>;

  getAgent(
    request: agent_pb.GetAgentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: agent_pb.Agent) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.AgentService/GetAgent',
        request,
        metadata || {},
        this.methodDescriptorGetAgent,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.AgentService/GetAgent',
    request,
    metadata || {},
    this.methodDescriptorGetAgent);
  }

  methodDescriptorUpdateAgent = new grpcWeb.MethodDescriptor(
    '/api.AgentService/UpdateAgent',
    grpcWeb.MethodType.UNARY,
    agent_pb.UpdateAgentRequest,
    agent_pb.Agent,
    (request: agent_pb.UpdateAgentRequest) => {
      return request.serializeBinary();
    },
    agent_pb.Agent.deserializeBinary
  );

  updateAgent(
    request: agent_pb.UpdateAgentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<agent_pb.Agent>;

  updateAgent(
    request: agent_pb.UpdateAgentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: agent_pb.Agent) => void): grpcWeb.ClientReadableStream<agent_pb.Agent>;

  updateAgent(
    request: agent_pb.UpdateAgentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: agent_pb.Agent) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.AgentService/UpdateAgent',
        request,
        metadata || {},
        this.methodDescriptorUpdateAgent,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.AgentService/UpdateAgent',
    request,
    metadata || {},
    this.methodDescriptorUpdateAgent);
  }

  methodDescriptorDeleteAgent = new grpcWeb.MethodDescriptor(
    '/api.AgentService/DeleteAgent',
    grpcWeb.MethodType.UNARY,
    agent_pb.DeleteAgentRequest,
    google_protobuf_empty_pb.Empty,
    (request: agent_pb.DeleteAgentRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteAgent(
    request: agent_pb.DeleteAgentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteAgent(
    request: agent_pb.DeleteAgentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteAgent(
    request: agent_pb.DeleteAgentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.AgentService/DeleteAgent',
        request,
        metadata || {},
        this.methodDescriptorDeleteAgent,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.AgentService/DeleteAgent',
    request,
    metadata || {},
    this.methodDescriptorDeleteAgent);
  }

}

