/**
 * @fileoverview gRPC-Web generated client stub for api
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.1
// source: tool.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as tool_pb from './tool_pb'; // proto import: "tool.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class ToolServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateTool = new grpcWeb.MethodDescriptor(
    '/api.ToolService/CreateTool',
    grpcWeb.MethodType.UNARY,
    tool_pb.CreateToolRequest,
    tool_pb.Tool,
    (request: tool_pb.CreateToolRequest) => {
      return request.serializeBinary();
    },
    tool_pb.Tool.deserializeBinary
  );

  createTool(
    request: tool_pb.CreateToolRequest,
    metadata?: grpcWeb.Metadata | null): Promise<tool_pb.Tool>;

  createTool(
    request: tool_pb.CreateToolRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: tool_pb.Tool) => void): grpcWeb.ClientReadableStream<tool_pb.Tool>;

  createTool(
    request: tool_pb.CreateToolRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: tool_pb.Tool) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.ToolService/CreateTool',
        request,
        metadata || {},
        this.methodDescriptorCreateTool,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.ToolService/CreateTool',
    request,
    metadata || {},
    this.methodDescriptorCreateTool);
  }

  methodDescriptorListTools = new grpcWeb.MethodDescriptor(
    '/api.ToolService/ListTools',
    grpcWeb.MethodType.UNARY,
    tool_pb.ListToolsRequest,
    tool_pb.ListToolsResponse,
    (request: tool_pb.ListToolsRequest) => {
      return request.serializeBinary();
    },
    tool_pb.ListToolsResponse.deserializeBinary
  );

  listTools(
    request: tool_pb.ListToolsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<tool_pb.ListToolsResponse>;

  listTools(
    request: tool_pb.ListToolsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: tool_pb.ListToolsResponse) => void): grpcWeb.ClientReadableStream<tool_pb.ListToolsResponse>;

  listTools(
    request: tool_pb.ListToolsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: tool_pb.ListToolsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.ToolService/ListTools',
        request,
        metadata || {},
        this.methodDescriptorListTools,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.ToolService/ListTools',
    request,
    metadata || {},
    this.methodDescriptorListTools);
  }

  methodDescriptorGetTool = new grpcWeb.MethodDescriptor(
    '/api.ToolService/GetTool',
    grpcWeb.MethodType.UNARY,
    tool_pb.GetToolRequest,
    tool_pb.Tool,
    (request: tool_pb.GetToolRequest) => {
      return request.serializeBinary();
    },
    tool_pb.Tool.deserializeBinary
  );

  getTool(
    request: tool_pb.GetToolRequest,
    metadata?: grpcWeb.Metadata | null): Promise<tool_pb.Tool>;

  getTool(
    request: tool_pb.GetToolRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: tool_pb.Tool) => void): grpcWeb.ClientReadableStream<tool_pb.Tool>;

  getTool(
    request: tool_pb.GetToolRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: tool_pb.Tool) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.ToolService/GetTool',
        request,
        metadata || {},
        this.methodDescriptorGetTool,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.ToolService/GetTool',
    request,
    metadata || {},
    this.methodDescriptorGetTool);
  }

  methodDescriptorDeleteTool = new grpcWeb.MethodDescriptor(
    '/api.ToolService/DeleteTool',
    grpcWeb.MethodType.UNARY,
    tool_pb.DeleteToolRequest,
    google_protobuf_empty_pb.Empty,
    (request: tool_pb.DeleteToolRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteTool(
    request: tool_pb.DeleteToolRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteTool(
    request: tool_pb.DeleteToolRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteTool(
    request: tool_pb.DeleteToolRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.ToolService/DeleteTool',
        request,
        metadata || {},
        this.methodDescriptorDeleteTool,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.ToolService/DeleteTool',
    request,
    metadata || {},
    this.methodDescriptorDeleteTool);
  }

}

