// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Agent is the predicate function for agent builders.
type Agent func(*sql.Selector)

// Conversation is the predicate function for conversation builders.
type Conversation func(*sql.Selector)

// DocumentChunk is the predicate function for documentchunk builders.
type DocumentChunk func(*sql.Selector)

// KnowledgeBase is the predicate function for knowledgebase builders.
type KnowledgeBase func(*sql.Selector)

// Tool is the predicate function for tool builders.
type Tool func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Workflow is the predicate function for workflow builders.
type Workflow func(*sql.Selector)

// WorkflowExecution is the predicate function for workflowexecution builders.
type WorkflowExecution func(*sql.Selector)
